// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/html/entities.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

// ---------------------------------------------------------------------------
// One HTML entity decoder for every import path.
//
// There used to be a copy of this in `lib/scrape/parse.ts`, another in
// `lib/import/htmlToSections.ts` and a third in `convex/import/blog.ts`, each
// handling the same six entities (`&amp;` `&quot;` `&#39;` `&lt;` `&gt;`
// `&nbsp;`). Every Swedish site whose CMS emits `&aring;` / `&auml;` / `&ouml;`
// instead of UTF-8 literals therefore imported its own copy as mojibake
// ("h&aring;llbarhet"), and — worse — the vertical/service classifiers match
// keywords like "städ", "frisör", "tandläkare" against that text, so such a
// page could never classify as anything but generic.
//
// Pure and dependency-free: it runs inside Convex actions and is unit-testable.
// ---------------------------------------------------------------------------

/** Named entities we decode: the Latin-1 letters our markets actually use plus
 *  the typographic punctuation editors insert. Anything not listed is left
 *  verbatim — an unrecognised entity is better than a wrong character. */
const NAMED_ENTITIES: Record<string, string> = {
  amp: "&", quot: '"', apos: "'", lt: "<", gt: ">", nbsp: " ",
  // Nordic + common Latin-1 letters
  aring: "å", Aring: "Å", auml: "ä", Auml: "Ä", ouml: "ö", Ouml: "Ö",
  aelig: "æ", AElig: "Æ", oslash: "ø", Oslash: "Ø",
  eacute: "é", Eacute: "É", egrave: "è", Egrave: "È", ecirc: "ê",
  agrave: "à", Agrave: "À", acirc: "â", uuml: "ü", Uuml: "Ü",
  ugrave: "ù", ucirc: "û", ccedil: "ç", Ccedil: "Ç", ntilde: "ñ",
  Ntilde: "Ñ", iacute: "í", oacute: "ó", uacute: "ú", szlig: "ß",
  // typographic punctuation
  ndash: "–", mdash: "—", hellip: "…", bull: "•", middot: "·",
  lsquo: "‘", rsquo: "’", sbquo: "‚",
  ldquo: "“", rdquo: "”", bdquo: "„",
  laquo: "«", raquo: "»", prime: "′", Prime: "″",
  // symbols
  copy: "©", reg: "®", trade: "™", deg: "°", euro: "€", pound: "£",
  yen: "¥", cent: "¢", sect: "§", para: "¶", times: "×", divide: "÷",
  plusmn: "±", frac12: "½", frac14: "¼", sup2: "²", sup3: "³",
  // zero-width / soft hyphen: drop rather than render as a literal
  shy: "", zwnj: "", zwj: "",
};

/** Decode HTML entities in ONE pass: the named set above plus decimal
 *  (`&#229;`) and hex (`&#xE5;`) numeric references.
 *
 *  Single-pass is deliberate. `&amp;aring;` is the literal text "&aring;", not
 *  "å"; re-running the decoder over its own output would turn escaped markup
 *  back into markup. */
export function decodeHtmlEntities(s: string): string {
  return s.replace(
    /&(#[0-9]{1,7}|#[xX][0-9a-fA-F]{1,6}|[a-zA-Z][a-zA-Z0-9]{1,31});/g,
    (whole, body: string) => {
      if (body.charCodeAt(0) === 35 /* # */) {
        const hex = body[1] === "x" || body[1] === "X";
        const code = Number.parseInt(hex ? body.slice(2) : body.slice(1), hex ? 16 : 10);
        if (!Number.isFinite(code) || code <= 0 || code > 0x10ffff) return whole;
        // Lone surrogate halves are not valid standalone code points.
        if (code >= 0xd800 && code <= 0xdfff) return whole;
        try {
          return String.fromCodePoint(code);
        } catch {
          return whole;
        }
      }
      const hit = NAMED_ENTITIES[body];
      return hit === undefined ? whole : hit;
    },
  );
}
