// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:convex/model/serviceSuggestions.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

import type { Vertical } from "../../../convex/model/business";

// ---------------------------------------------------------------------------
// Plain-language service suggestions per business vertical, used to pre-fill
// the services section during onboarding so a non-technical owner can pick from
// realistic options instead of typing from scratch. Trilingual (sv/en/pl); keep
// labels short and jargon-free (see product principles).
// ---------------------------------------------------------------------------

export const SERVICE_SUGGESTIONS: Record<
  Vertical,
  { sv: string; en: string; pl: string }[]
> = {
  animals: [
    { sv: "Pälsvård och trim", en: "Grooming and trimming", pl: "Pielęgnacja i strzyżenie" },
    { sv: "Bad och borstning", en: "Bath and brushing", pl: "Kąpiel i szczotkowanie" },
    { sv: "Klovård", en: "Nail care", pl: "Pielęgnacja pazurów" },
    { sv: "Urtovning", en: "De-matting", pl: "Rozczesywanie kołtunów" },
    { sv: "Öron och tänder", en: "Ears and teeth", pl: "Uszy i zęby" },
    { sv: "Valpens första besök", en: "A puppy's first visit", pl: "Pierwsza wizyta szczeniaka" },
    { sv: "Hunddagis", en: "Dog day care", pl: "Przedszkole dla psów" },
    { sv: "Pensionat", en: "Boarding", pl: "Hotel dla zwierząt" },
    { sv: "Hundpromenad", en: "Dog walking", pl: "Wyprowadzanie psów" },
    { sv: "Kattklippning", en: "Cat grooming", pl: "Strzyżenie kotów" },
  ],
  retail: [
    { sv: "Sortiment", en: "Our range", pl: "Asortyment" },
    { sv: "Beställning av varor", en: "Special orders", pl: "Zamówienia towaru" },
    { sv: "Presentkort", en: "Gift cards", pl: "Karty podarunkowe" },
    { sv: "Personlig rådgivning", en: "Personal advice", pl: "Osobiste doradztwo" },
    { sv: "Inslagning", en: "Gift wrapping", pl: "Pakowanie na prezent" },
    { sv: "Hemleverans", en: "Home delivery", pl: "Dostawa do domu" },
    { sv: "Företagsbeställningar", en: "Business orders", pl: "Zamówienia firmowe" },
    { sv: "Reparation och service", en: "Repairs and servicing", pl: "Naprawa i serwis" },
    { sv: "Second hand och inbyte", en: "Second hand and trade-in", pl: "Second hand i wymiana" },
    { sv: "Avhämtning i butik", en: "Collection in store", pl: "Odbiór w sklepie" },
  ],
  hotel: [
    { sv: "Dubbelrum", en: "Double room", pl: "Pokój dwuosobowy" },
    { sv: "Enkelrum", en: "Single room", pl: "Pokój jednoosobowy" },
    { sv: "Familjerum", en: "Family room", pl: "Pokój rodzinny" },
    { sv: "Svit", en: "Suite", pl: "Apartament" },
    { sv: "Frukost", en: "Breakfast", pl: "Śniadanie" },
    { sv: "Uthyrning av stuga", en: "Cottage rental", pl: "Wynajem domku" },
    { sv: "Konferens och möten", en: "Conferences and meetings", pl: "Konferencje i spotkania" },
    { sv: "Långtidsboende", en: "Long stays", pl: "Pobyty długoterminowe" },
    { sv: "Sen utcheckning", en: "Late checkout", pl: "Późne wymeldowanie" },
    { sv: "Bastu och relax", en: "Sauna and relaxation", pl: "Sauna i relaks" },
  ],
  school: [
    { sv: "Lektion", en: "Lesson", pl: "Lekcja" },
    { sv: "Nybörjarkurs", en: "Beginners' course", pl: "Kurs dla początkujących" },
    { sv: "Fortsättningskurs", en: "Follow-on course", pl: "Kurs kontynuacyjny" },
    { sv: "Intensivkurs", en: "Intensive course", pl: "Kurs intensywny" },
    { sv: "Privatlektion", en: "Private lesson", pl: "Lekcja indywidualna" },
    { sv: "Gruppundervisning", en: "Group teaching", pl: "Zajęcia grupowe" },
    { sv: "Kurs på distans", en: "Online course", pl: "Kurs online" },
    { sv: "Provlektion", en: "Trial lesson", pl: "Lekcja próbna" },
    { sv: "Företagsutbildning", en: "Training for businesses", pl: "Szkolenia dla firm" },
    { sv: "Presentkort på lektion", en: "Lesson gift card", pl: "Karta podarunkowa na lekcję" },
  ],
  autoshop: [
    { sv: "Service", en: "Servicing", pl: "Serwis" },
    { sv: "Reparation", en: "Repair", pl: "Naprawa" },
    { sv: "Felsökning", en: "Fault tracing", pl: "Diagnostyka" },
    { sv: "Bromsar", en: "Brakes", pl: "Hamulce" },
    { sv: "Däckskifte", en: "Tyre change", pl: "Wymiana opon" },
    { sv: "Hjulinställning", en: "Wheel alignment", pl: "Geometria kół" },
    { sv: "AC-service", en: "Air-conditioning service", pl: "Serwis klimatyzacji" },
    { sv: "Batteribyte", en: "Battery replacement", pl: "Wymiana akumulatora" },
    { sv: "Kamrem", en: "Timing belt", pl: "Pasek rozrządu" },
    { sv: "Hjälp inför besiktning", en: "Pre-inspection check", pl: "Przygotowanie do przeglądu" },
  ],
  dentist: [
    { sv: "Undersökning", en: "Checkup", pl: "Przegląd" },
    { sv: "Tandhygienist", en: "Hygienist", pl: "Higienistka" },
    { sv: "Tandblekning", en: "Teeth whitening", pl: "Wybielanie zębów" },
    { sv: "Tandfyllning", en: "Fillings", pl: "Wypełnienia" },
    { sv: "Implantat", en: "Implants", pl: "Implanty" },
    { sv: "Krona", en: "Crown", pl: "Korona" },
    { sv: "Rotfyllning", en: "Root canal", pl: "Leczenie kanałowe" },
    { sv: "Tandreglering", en: "Braces", pl: "Aparat ortodontyczny" },
    { sv: "Barntandvård", en: "Children's dentistry", pl: "Stomatologia dziecięca" },
    { sv: "Akuttandvård", en: "Emergency care", pl: "Pomoc doraźna" },
  ],
  clinic: [
    { sv: "Bedömning", en: "Assessment", pl: "Ocena" },
    { sv: "Behandling", en: "Treatment", pl: "Leczenie" },
    { sv: "Uppföljning", en: "Follow-up", pl: "Wizyta kontrolna" },
    { sv: "Rehabilitering", en: "Rehabilitation", pl: "Rehabilitacja" },
    { sv: "Förebyggande vård", en: "Preventive care", pl: "Profilaktyka" },
    { sv: "Rådgivning", en: "Advice", pl: "Porady" },
    { sv: "Hembesök", en: "Home visit", pl: "Wizyta domowa" },
    { sv: "Onlinebokning", en: "Online booking", pl: "Rezerwacja online" },
    { sv: "Akuttid", en: "Urgent appointment", pl: "Pilna wizyta" },
    { sv: "Friskvård", en: "Wellness", pl: "Wellness" },
  ],
  salon: [
    { sv: "Klippning", en: "Haircut", pl: "Strzyżenie" },
    { sv: "Barnklippning", en: "Kids haircut", pl: "Strzyżenie dzieci" },
    { sv: "Färgning", en: "Coloring", pl: "Koloryzacja" },
    { sv: "Slingor", en: "Highlights", pl: "Pasemka" },
    { sv: "Styling", en: "Styling", pl: "Stylizacja" },
    { sv: "Föning", en: "Blow-dry", pl: "Modelowanie" },
    { sv: "Permanent", en: "Perm", pl: "Trwała" },
    { sv: "Hårvård", en: "Hair treatment", pl: "Pielęgnacja włosów" },
    { sv: "Skägg", en: "Beard trim", pl: "Strzyżenie brody" },
    { sv: "Bröllop", en: "Bridal", pl: "Fryzura ślubna" },
  ],
  cleaning: [
    { sv: "Hemstädning", en: "Home cleaning", pl: "Sprzątanie domów" },
    { sv: "Veckostädning", en: "Weekly cleaning", pl: "Sprzątanie cotygodniowe" },
    { sv: "Flyttstädning", en: "Move-out cleaning", pl: "Sprzątanie po przeprowadzce" },
    { sv: "Kontorsstädning", en: "Office cleaning", pl: "Sprzątanie biur" },
    { sv: "Storstädning", en: "Deep clean", pl: "Sprzątanie generalne" },
    { sv: "Fönsterputs", en: "Window cleaning", pl: "Mycie okien" },
    { sv: "Byggstädning", en: "Construction cleanup", pl: "Sprzątanie po budowie" },
    { sv: "Visningsstädning", en: "Viewing cleaning", pl: "Sprzątanie przed prezentacją" },
    { sv: "Golvvård", en: "Floor care", pl: "Pielęgnacja podłóg" },
    { sv: "Trappstädning", en: "Stairwell cleaning", pl: "Sprzątanie klatek schodowych" },
  ],
  restaurant: [
    { sv: "Frukost", en: "Breakfast", pl: "Śniadanie" },
    { sv: "Brunch", en: "Brunch", pl: "Brunch" },
    { sv: "Lunch", en: "Lunch", pl: "Lunch" },
    { sv: "Middag", en: "Dinner", pl: "Kolacja" },
    { sv: "Fika", en: "Coffee & cake", pl: "Kawa i ciasto" },
    { sv: "Catering", en: "Catering", pl: "Catering" },
    { sv: "Avhämtning", en: "Takeaway", pl: "Na wynos" },
    { sv: "Hemkörning", en: "Delivery", pl: "Dostawa" },
    { sv: "Bordsbokning", en: "Table booking", pl: "Rezerwacja stolika" },
    { sv: "Privata event", en: "Private events", pl: "Imprezy prywatne" },
  ],
  fitness: [
    { sv: "Gym", en: "Gym", pl: "Siłownia" },
    { sv: "Personlig träning", en: "Personal training", pl: "Trening personalny" },
    { sv: "Gruppträning", en: "Group classes", pl: "Zajęcia grupowe" },
    { sv: "Yoga", en: "Yoga", pl: "Joga" },
    { sv: "Pilates", en: "Pilates", pl: "Pilates" },
    { sv: "Spinning", en: "Spinning", pl: "Spinning" },
    { sv: "Crossfit", en: "CrossFit", pl: "CrossFit" },
    { sv: "Boxning", en: "Boxing", pl: "Boks" },
    { sv: "Kostrådgivning", en: "Nutrition coaching", pl: "Poradnictwo żywieniowe" },
    { sv: "Onlinecoaching", en: "Online coaching", pl: "Coaching online" },
  ],
  handyman: [
    { sv: "Snickeri", en: "Carpentry", pl: "Stolarka" },
    { sv: "Målning", en: "Painting", pl: "Malowanie" },
    { sv: "Tapetsering", en: "Wallpapering", pl: "Tapetowanie" },
    { sv: "Golvläggning", en: "Flooring", pl: "Układanie podłóg" },
    { sv: "VVS", en: "Plumbing", pl: "Hydraulika" },
    { sv: "El", en: "Electrical", pl: "Elektryka" },
    { sv: "Badrum", en: "Bathroom", pl: "Łazienki" },
    { sv: "Tak", en: "Roofing", pl: "Dachy" },
    { sv: "Montering", en: "Assembly", pl: "Montaż" },
    { sv: "Renovering", en: "Renovation", pl: "Remonty" },
  ],
  consultant: [
    { sv: "Rådgivning", en: "Advisory", pl: "Doradztwo" },
    { sv: "Strategi", en: "Strategy", pl: "Strategia" },
    { sv: "Analys", en: "Analysis", pl: "Analiza" },
    { sv: "Projektledning", en: "Project management", pl: "Zarządzanie projektami" },
    { sv: "Workshop", en: "Workshop", pl: "Warsztaty" },
    { sv: "Utbildning", en: "Training", pl: "Szkolenia" },
    { sv: "Affärsutveckling", en: "Business development", pl: "Rozwój biznesu" },
    { sv: "Utvärdering", en: "Evaluation", pl: "Ocena" },
    { sv: "Förstudie", en: "Pre-study", pl: "Analiza wstępna" },
    { sv: "Interim", en: "Interim support", pl: "Wsparcie interim" },
  ],
  coach: [
    { sv: "Introsamtal", en: "Intro session", pl: "Sesja wstępna" },
    { sv: "Personlig coaching", en: "1-on-1 coaching", pl: "Coaching indywidualny" },
    { sv: "Onlinecoaching", en: "Online coaching", pl: "Coaching online" },
    { sv: "Grupprogram", en: "Group program", pl: "Program grupowy" },
    { sv: "Workshop", en: "Workshop", pl: "Warsztaty" },
    { sv: "Föreläsning", en: "Talk", pl: "Prelekcja" },
    { sv: "Karriärcoaching", en: "Career coaching", pl: "Coaching kariery" },
    { sv: "Ledarskapscoaching", en: "Leadership coaching", pl: "Coaching przywództwa" },
    { sv: "Uppföljning", en: "Follow-up", pl: "Sesja kontrolna" },
    { sv: "Program 8 veckor", en: "8-week program", pl: "Program 8 tygodni" },
  ],
  therapist: [
    { sv: "Första samtal", en: "Intro session", pl: "Pierwsza rozmowa" },
    { sv: "Individuell terapi", en: "Individual therapy", pl: "Terapia indywidualna" },
    { sv: "Parsamtal", en: "Couples sessions", pl: "Sesje dla par" },
    { sv: "Onlinesamtal", en: "Online sessions", pl: "Sesje online" },
    { sv: "Somatic Experiencing", en: "Somatic Experiencing", pl: "Somatic Experiencing" },
    { sv: "Traumabearbetning", en: "Trauma work", pl: "Praca z traumą" },
    { sv: "Stresshantering", en: "Stress management", pl: "Radzenie sobie ze stresem" },
    { sv: "Gruppterapi", en: "Group therapy", pl: "Terapia grupowa" },
  ],
  freelancer: [
    { sv: "Konsultation", en: "Consultation", pl: "Konsultacja" },
    { sv: "Projekt", en: "Project work", pl: "Praca projektowa" },
    { sv: "Timarvode", en: "Hourly work", pl: "Praca na godziny" },
    { sv: "Löpande uppdrag", en: "Ongoing work", pl: "Praca ciągła" },
    { sv: "Underhåll", en: "Maintenance", pl: "Utrzymanie" },
    { sv: "Workshop", en: "Workshop", pl: "Warsztaty" },
    { sv: "Rådgivning", en: "Advice", pl: "Porady" },
    { sv: "Offert", en: "Quote", pl: "Wycena" },
    { sv: "Snabbleverans", en: "Fast delivery", pl: "Szybka realizacja" },
    { sv: "Revidering", en: "Revisions", pl: "Poprawki" },
  ],
  generic: [
    { sv: "Konsultation", en: "Consultation", pl: "Konsultacja" },
    { sv: "Rådgivning", en: "Advice", pl: "Porady" },
    { sv: "Offert", en: "Quote", pl: "Wycena" },
    { sv: "Installation", en: "Installation", pl: "Montaż" },
    { sv: "Reparation", en: "Repair", pl: "Naprawa" },
    { sv: "Underhåll", en: "Maintenance", pl: "Utrzymanie" },
    { sv: "Support", en: "Support", pl: "Wsparcie" },
    { sv: "Leverans", en: "Delivery", pl: "Dostawa" },
  ],
};

export const PLUMBING_SERVICE_SUGGESTIONS: { sv: string; en: string; pl: string }[] = [
  { sv: "Akut läcka", en: "Emergency leak", pl: "Awaryjny wyciek" },
  { sv: "Avloppsstopp", en: "Blocked drain", pl: "Zatkany odpływ" },
  { sv: "Rördragning", en: "Pipe installation", pl: "Montaż rur" },
  { sv: "Värmepumpar", en: "Heat pumps", pl: "Pompy ciepła" },
  { sv: "Badrum", en: "Bathroom plumbing", pl: "Instalacje łazienkowe" },
  { sv: "Blandare", en: "Mixer taps", pl: "Baterie" },
  { sv: "Vattenläcka", en: "Water leak", pl: "Wyciek wody" },
  { sv: "Golvvärme", en: "Underfloor heating", pl: "Ogrzewanie podłogowe" },
  { sv: "Serviceavtal", en: "Service agreements", pl: "Umowy serwisowe" },
  { sv: "Jour", en: "Emergency callout", pl: "Pogotowie" },
];

const PLUMBING_KEYWORD_STEMS = [
  "vvs",
  "rormok",
  "rorproblem",
  "rorjour",
  "avlopp",
  "lacka",
  "lackage",
  "vattenlack",
  "vattenledning",
  "varmepump",
  "golvvarme",
  "blandare",
  "plumb",
  "plumber",
  "pipe",
  "drain",
  "leak",
  "heat pump",
];

function normalizeProfileText(value: string): string {
  return value
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .toLocaleLowerCase("sv-SE");
}

export function isPlumbingProfileText(value: string | null | undefined): boolean {
  if (!value) return false;
  const text = normalizeProfileText(value);
  return PLUMBING_KEYWORD_STEMS.some((stem) => text.includes(stem));
}

export function hasPlumbingProfile(args: {
  vertical?: Vertical | string | null;
  text?: string | null;
  services?: readonly string[] | null;
}): boolean {
  const vertical = args.vertical ?? "generic";
  if (vertical !== "handyman" && vertical !== "generic") return false;
  return isPlumbingProfileText(
    [args.text, ...(args.services ?? [])].filter(Boolean).join(" "),
  );
}

// ---------------------------------------------------------------------------
// Keyword-profile suggestion tables (audit C2-07). Crafts without a curated
// vertical — florists, photographers, designers, writers, videographers —
// land in generic/freelancer and used to get trades-and-consulting chips
// (Installation/Reparation for a florist), undoing the "vi förstår er
// bransch" feel the extraction just established. When the owner's own words
// name the craft, suggest services from that craft instead. Stems are matched
// against diacritic-stripped text (normalizeProfileText).
// ---------------------------------------------------------------------------
const PROFILE_SUGGESTIONS: Array<{
  stems: string[];
  match?: RegExp;
  suggestions: { sv: string; en: string; pl: string }[];
}> = [
  {
    stems: ["blomster", "florist", "blommor", "bukett", "binderi", "flower"],
    suggestions: [
      { sv: "Buketter", en: "Bouquets", pl: "Bukiety" },
      { sv: "Bröllopsblommor", en: "Wedding flowers", pl: "Kwiaty ślubne" },
      { sv: "Begravningsbinderi", en: "Funeral arrangements", pl: "Wiązanki pogrzebowe" },
      { sv: "Företagsblommor", en: "Corporate flowers", pl: "Kwiaty dla firm" },
      { sv: "Blomsterprenumeration", en: "Flower subscription", pl: "Subskrypcja kwiatowa" },
      { sv: "Eventdekoration", en: "Event decoration", pl: "Dekoracje eventowe" },
      { sv: "Krukväxter", en: "Potted plants", pl: "Rośliny doniczkowe" },
      { sv: "Leverans", en: "Delivery", pl: "Dostawa" },
    ],
  },
  {
    // Exact foto/photo words plus common Swedish compounds cover prompts that
    // name the craft without the trade noun, without treating unrelated words
    // such as "photovoltaic"/"fotovoltaik" as photography.
    stems: ["fotograf", "photograph"],
    match: /(?:^|\s)(?:foto|photo)(?:\s|$)|(?:foretags|brollops|portratt|produkt|event|studio)foto\b/u,
    suggestions: [
      { sv: "Porträttfoto", en: "Portrait photography", pl: "Fotografia portretowa" },
      { sv: "Bröllopsfoto", en: "Wedding photography", pl: "Fotografia ślubna" },
      { sv: "Företagsfoto", en: "Corporate photography", pl: "Fotografia biznesowa" },
      { sv: "Produktfoto", en: "Product photography", pl: "Fotografia produktowa" },
      { sv: "Eventfoto", en: "Event photography", pl: "Fotografia eventowa" },
      { sv: "Familjefoto", en: "Family photography", pl: "Fotografia rodzinna" },
      { sv: "Studiofoto", en: "Studio sessions", pl: "Sesje studyjne" },
      { sv: "Bildredigering", en: "Photo editing", pl: "Edycja zdjęć" },
    ],
  },
  {
    stems: ["videograf", "filmare", "videographer", "filmmaker"],
    suggestions: [
      { sv: "Företagsfilm", en: "Corporate video", pl: "Film firmowy" },
      { sv: "Reklamfilm", en: "Commercials", pl: "Filmy reklamowe" },
      { sv: "Eventfilm", en: "Event video", pl: "Filmy eventowe" },
      { sv: "Bröllopsfilm", en: "Wedding video", pl: "Filmy ślubne" },
      { sv: "Drönarfilm", en: "Drone footage", pl: "Ujęcia z drona" },
      { sv: "Klipp för sociala medier", en: "Social media clips", pl: "Klipy do social mediów" },
      { sv: "Redigering", en: "Editing", pl: "Montaż" },
    ],
  },
  {
    stems: ["designer", "formgivare", "illustrat", "grafisk design"],
    suggestions: [
      { sv: "Logotyp", en: "Logo design", pl: "Projekt logo" },
      { sv: "Grafisk profil", en: "Brand identity", pl: "Identyfikacja wizualna" },
      { sv: "Webbdesign", en: "Web design", pl: "Projektowanie stron" },
      { sv: "Trycksaker", en: "Print design", pl: "Materiały drukowane" },
      { sv: "Illustration", en: "Illustration", pl: "Ilustracje" },
      { sv: "Förpackningsdesign", en: "Packaging design", pl: "Projekt opakowań" },
      { sv: "Presentationer", en: "Presentations", pl: "Prezentacje" },
    ],
  },
  {
    stems: ["skribent", "copywriter"],
    suggestions: [
      { sv: "Webbtexter", en: "Website copy", pl: "Teksty na strony" },
      { sv: "Artiklar", en: "Articles", pl: "Artykuły" },
      { sv: "Nyhetsbrev", en: "Newsletters", pl: "Newslettery" },
      { sv: "SEO-texter", en: "SEO copy", pl: "Teksty SEO" },
      { sv: "Produkttexter", en: "Product copy", pl: "Opisy produktów" },
      { sv: "Korrekturläsning", en: "Proofreading", pl: "Korekta" },
    ],
  },
];

function profileSuggestionsFor(
  text: string,
): { sv: string; en: string; pl: string }[] | undefined {
  const normalized = normalizeProfileText(text);
  return PROFILE_SUGGESTIONS.find(
    (p) => p.match?.test(normalized) || p.stems.some((stem) => normalized.includes(stem)),
  )?.suggestions;
}

function localizeSuggestions(
  suggestions: { sv: string; en: string; pl: string }[],
  locale: string,
): string[] {
  return suggestions.map((s) => (s as Record<string, string>)[locale] ?? s.en);
}

export function getServiceSuggestions(
  vertical: Vertical,
  locale: string,
): string[] {
  return localizeSuggestions(SERVICE_SUGGESTIONS[vertical], locale);
}

export function getServiceSuggestionsForProfile(
  vertical: Vertical,
  locale: string,
  profile?: { text?: string | null; services?: readonly string[] | null },
): string[] {
  if (
    hasPlumbingProfile({
      vertical,
      text: profile?.text,
      services: profile?.services,
    })
  ) {
    return localizeSuggestions(PLUMBING_SERVICE_SUGGESTIONS, locale);
  }
  // Craft-specific chips only where the fallback tables are generic; curated
  // verticals (dentist, restaurant, …) keep their own tables.
  if (vertical === "generic" || vertical === "freelancer") {
    const fromProfile = profileSuggestionsFor(
      [profile?.text, ...(profile?.services ?? [])].filter(Boolean).join(" "),
    );
    if (fromProfile) return localizeSuggestions(fromProfile, locale);
  }
  return localizeSuggestions(SERVICE_SUGGESTIONS[vertical], locale);
}
