// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/scrape/bokadirekt.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

// ---------------------------------------------------------------------------
// Bokadirekt-specific extraction. Bokadirekt (bokadirekt.se) is the dominant
// Swedish salon/clinic/wellness booking platform; many small businesses have a
// Bokadirekt profile but no website. Their profile pages are SERVER-RENDERED -
// business name, address, phone and the price-listed service menu are all in the
// HTML as readable text - so we can seed onboarding from a pasted Bokadirekt URL
// and wire the site's "Boka" button straight to it.
//
// Pure (no DOM, no network) so it's unit-testable, like parse.ts. BEST-EFFORT:
// returns whatever it can find. Name/address/phone are reliable; the service
// menu is heuristic (the owner edits the result), so it's filtered conservatively
// rather than risking garbage entries.
// ---------------------------------------------------------------------------

import { parseLocalBusinessProfile, seedableReviews } from "../external/localBusiness";

/** What a visitor sees beside a quoted review. */
const SOURCE_LABEL = "Bokadirekt";

export type BokadirektResult = {
  businessName?: string;
  phone?: string;
  /** Street + postal code. */
  address?: string;
  /** Locality (maps to the onboarding "City" field). */
  city?: string;
  /** Service names from the price menu (best-effort, deduped, capped). */
  services?: string[];
  /** Contact address from the profile's structured data, when published. */
  email?: string;
  /** Real customer quotes the business already earned, each carrying its source
   *  in the author line — these are borrowed, not ours (see `seedableReviews`). */
  testimonials?: Array<{ text: string; author?: string; rating?: number }>;
};

function decodeEntities(s: string): string {
  return s
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&#0?39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&nbsp;/g, " ");
}

/** Strip scripts/styles/tags → readable text with collapsed whitespace. */
function toText(html: string): string {
  return decodeEntities(
    html
      .replace(/<script[\s\S]*?<\/script>/gi, " ")
      .replace(/<style[\s\S]*?<\/style>/gi, " ")
      .replace(/<[^>]+>/g, " "),
  )
    .replace(/\s+/g, " ")
    .trim();
}

function metaContent(html: string, keys: string[]): string | undefined {
  for (const key of keys) {
    const k = key.replace(/[:]/g, "\\:");
    const m =
      html.match(
        new RegExp(
          `<meta[^>]+(?:property|name)=["']${k}["'][^>]*content=["']([^"']*)["']`,
          "i",
        ),
      ) ??
      html.match(
        new RegExp(
          `<meta[^>]+content=["']([^"']*)["'][^>]*(?:property|name)=["']${k}["']`,
          "i",
        ),
      );
    if (m?.[1]) return decodeEntities(m[1]).trim();
  }
  return undefined;
}

/** Clean a Bokadirekt page title into a business name: drop the " - Bokadirekt"
 *  / " | Bokadirekt" suffix and a trailing ", <City>". */
function cleanName(raw: string): string {
  let s = raw.trim();
  // strip provider suffix
  s = s.replace(/\s*[|\-–—]\s*Bokadirekt\s*$/i, "").trim();
  // strip a trailing ", City" (single segment, letters only)
  s = s.replace(/,\s*[\p{L}\s.-]{2,40}$/u, "").trim();
  return s.slice(0, 80);
}

/** The page's JSON-LD LocalBusiness/Organization node, if any.
 *  `@type` may be a STRING **or an ARRAY** - both are valid JSON-LD, and real
 *  pages emit arrays like `["LocalBusiness","HealthAndBeautyBusiness"]`. A
 *  string-only check silently skipped every such page (backlog 0279). */
function businessNodeFromJsonLd(
  html: string,
): Record<string, unknown> | undefined {
  const blocks = html.matchAll(
    /<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi,
  );
  for (const b of blocks) {
    try {
      const json = JSON.parse(b[1].trim());
      const nodes = Array.isArray(json) ? json : [json];
      for (const node of nodes) {
        const raw = node?.["@type"];
        const types = Array.isArray(raw) ? raw : [raw];
        const isBusiness = types.some(
          (t) => typeof t === "string" && /LocalBusiness|Organization/i.test(t),
        );
        if (isBusiness) return node as Record<string, unknown>;
      }
    } catch {
      // ignore malformed JSON-LD
    }
  }
  return undefined;
}

const ldString = (v: unknown): string | undefined =>
  typeof v === "string" && v.trim() ? v.trim().slice(0, 80) : undefined;

/** The business name from the page's JSON-LD LocalBusiness node (the cleanest
 *  source - the visible `og:site_name` is the platform "Bokadirekt"). */
function nameFromJsonLd(html: string): string | undefined {
  return ldString(businessNodeFromJsonLd(html)?.name);
}

/** The STRUCTURED address from the JSON-LD node. Preferred over the flat-text
 *  regex in `parseBokadirekt`: `toText` collapses all whitespace, so that regex
 *  must stop the locality at the first space or it would swallow the following
 *  page prose ("Jönköping Tjänster …") - which truncates a real multi-word
 *  locality like "Upplands Väsby". A `PostalAddress` has exact field
 *  boundaries, so there is nothing to guess (backlog 0279). */
function addressFromJsonLd(
  html: string,
): { street?: string; postalCode?: string; city?: string } | undefined {
  const addr = businessNodeFromJsonLd(html)?.address;
  if (!addr || typeof addr !== "object") return undefined;
  const a = addr as Record<string, unknown>;
  const out = {
    street: ldString(a.streetAddress),
    postalCode: ldString(a.postalCode),
    city: ldString(a.addressLocality),
  };
  return out.street || out.postalCode || out.city ? out : undefined;
}

const SERVICE_NAME_RE = /^[\p{L}][\p{L}0-9()&/.,'’\- ]{1,38}$/u;

/** Bokadirekt service rows flatten to "<name> <dd> min [desc] Pris<price> kr"
 *  (or "… Från <price> kr"). We anchor on the price token, then take the text
 *  just before the "<dd> min" duration as the service name. Best-effort. */
function removeFirstServiceContext(name: string, city?: string): string {
  if (!city) return name;
  const lowerName = name.toLocaleLowerCase("sv");
  for (const heading of ["Alla tjänster", "Tjänster"]) {
    const prefix = `${city} ${heading} `;
    if (lowerName.startsWith(prefix.toLocaleLowerCase("sv"))) {
      return name.slice(prefix.length);
    }
  }
  return name;
}

function extractServices(text: string, city?: string): string[] {
  const out: string[] = [];
  const seen = new Set<string>();
  let isFirstCandidate = true;
  // name (lazy) + duration + (within a short window) a price token.
  // The name class excludes digits so it can't span back across an address
  // number / postal code into the previous block.
  const re =
    /([\p{L}][\p{L}()&/.,'’\- ]{1,38}?)\s+(\d{1,3})\s*min\b[\s\S]{0,80}?(?:Pris|Från)\s*[\d\s]{2,9}kr/giu;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) {
    // keep only the last 6 words before the duration - earlier words bleed in
    // from the previous service's tail in the flattened text - then drop the
    // leading "Boka" that precedes each row's name on a Bokadirekt page.
    let name = m[1]
      .trim()
      .split(/\s+/)
      .slice(-6)
      .join(" ")
      .replace(/^Boka\s+/i, "")
      .trim();
    // The first row has no previous price boundary, so flattened fallback
    // markup may include the known city + service-section heading. Match that
    // exact context so a real service named "Tjänster för barn" stays intact.
    if (isFirstCandidate) name = removeFirstServiceContext(name, city);
    isFirstCandidate = false;
    if (!SERVICE_NAME_RE.test(name)) continue;
    const key = name.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(name);
    if (out.length >= 12) break;
  }
  return out;
}

/** `sourceUrl` is the profile page the reviews came from; it is carried so a
 *  future testimonials schema can link back. Optional so existing callers keep
 *  working. */
export function parseBokadirekt(html: string, sourceUrl?: string): BokadirektResult {
  const result: BokadirektResult = {};
  const text = toText(html);

  // --- name (JSON-LD LocalBusiness, else og:title / <title>, cleaned) ---
  // NB: og:site_name is the platform ("Bokadirekt"), never the place - skip it.
  const ldName = nameFromJsonLd(html);
  if (ldName) {
    result.businessName = ldName;
  } else {
    const rawName =
      metaContent(html, ["og:title"]) ??
      html.match(/<title[^>]*>([^<]*)<\/title>/i)?.[1];
    if (rawName) {
      const name = cleanName(decodeEntities(rawName));
      if (name) result.businessName = name;
    }
  }

  // --- address: structured JSON-LD first, flat text as fallback ---
  // The JSON-LD PostalAddress has exact field boundaries, so it handles a
  // multi-word locality ("Upplands Väsby") that the text regex below cannot
  // (backlog 0279).
  const ldAddr = addressFromJsonLd(html);
  if (ldAddr?.city) result.city = ldAddr.city;
  if (ldAddr?.street || ldAddr?.postalCode) {
    result.address = [ldAddr.street, ldAddr.postalCode]
      .filter(Boolean)
      .join(", ")
      .slice(0, 120);
  }

  // Fallback for pages with no JSON-LD address: Swedish "Street 12, 553 21
  // Jönköping". Anchor on the postal code + city (unique, reliable), then take
  // the street as the 1-2 words + number immediately before it. A single greedy
  // regex would bleed preceding page text (title/nav) into the street, so we do
  // it in steps. The locality stops at the first space on purpose: `toText`
  // collapses all whitespace, so a wider match would swallow the page prose that
  // follows the address.
  if (!result.address || !result.city) {
    const postal = text.match(
      /(\d{3}\s?\d{2})\s+([\p{L}][\p{L} .\-]{1,30}?)(?=$|[,\s])/u,
    );
    if (postal) {
      const postalCode = postal[1].replace(/\s+/g, " ").trim();
      const locality = postal[2].trim();
      if (locality && !result.city) result.city = locality.slice(0, 80);
      if (!result.address) {
        // text before the postal, minus a trailing comma/space separator.
        const before = text.slice(0, postal.index).replace(/[,\s]+$/, "");
        const street = before.match(
          /([\p{L}][\p{L}.'’\-]+(?:\s+[\p{L}.'’\-]+)?)\s+(\d+[A-Za-z]?)$/u,
        );
        result.address = (
          street ? `${street[1]} ${street[2]}, ${postalCode}` : postalCode
        ).slice(0, 120);
      }
    }
  }

  // --- phone: tel: link first, else a Swedish number in text ---
  const tel = html.match(/href=["']tel:([^"']+)["']/i)?.[1];
  if (tel) {
    result.phone = decodeURIComponent(tel).trim().slice(0, 40);
  } else {
    const ph = text.match(/(\+?46[\s\-]?|0)\s?\d{1,3}([\s\-]?\d{2,3}){2,4}/);
    if (ph) result.phone = ph[0].replace(/\s+/g, " ").trim().slice(0, 40);
  }

  // --- service menu (best-effort) ---
  const services = extractServices(text, result.city);
  if (services.length) result.services = services;

  // --- what only the structured data has: email, and the reviews ---
  // The heuristics above cannot reach either. A Bokadirekt profile publishes
  // schema.org `LocalBusiness` with the contact address and the salon's own
  // reviews, and the shared parser (lib/external/localBusiness.ts) reads the
  // same shape on any platform that does it.
  const profile = parseLocalBusinessProfile(html, SOURCE_LABEL, sourceUrl ?? "");
  if (profile) {
    if (profile.email) result.email = profile.email.slice(0, 120);
    const quotes = seedableReviews(profile);
    if (quotes.length) {
      result.testimonials = quotes.map((r) => ({
        text: r.text,
        // Attribution lives in the author line because the testimonials content
        // schema has no source field. These reviews belong to the platform the
        // customer wrote them on; reprinting them unmarked would be dishonest
        // and, to a search engine, duplicate content.
        author: `${r.author} · ${r.sourceLabel}`,
        ...(typeof r.rating === "number" ? { rating: r.rating } : {}),
      }));
    }
  }

  return result;
}
