// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/scrape/classifyVertical.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

import type { Vertical } from "../../../convex/model/business";

// ---------------------------------------------------------------------------
// Best-guess business vertical from scraped page content. Pure + dependency-
// free so it runs inside the Convex `scrapeSite` action and is unit-testable.
// It's a SUGGESTION only - onboarding pre-selects the guess but the owner can
// always change it. Low/zero signal → "generic" (the "Something else" card).
//
// Scoring: each vertical owns a set of bilingual (sv/en) keywords split into
// `strong` (weight 3 - names the trade itself) and `weak` (weight 1 - a service
// or adjacent term). We count each distinct matched keyword once and pick the
// top-scoring vertical. "confident" requires a clear strong signal AND a margin
// over the runner-up, so an ambiguous page stays a soft suggestion.
// ---------------------------------------------------------------------------

type Trade = Exclude<Vertical, "generic">;

const KEYWORDS: Record<Trade, { strong: string[]; weak: string[] }> = {
  dentist: {
    strong: ["tandläkare", "tandvård", "tandklinik", "dentist", "dental"],
    weak: [
      "tandhygienist",
      "tandblekning",
      "implantat",
      "rotfyllning",
      "tandreglering",
      "hygienist",
      "orthodont",
    ],
  },
  clinic: {
    strong: [
      "klinik",
      "mottagning",
      "vårdcentral",
      "fysioterapeut",
      "naprapat",
      "kiropraktor",
      "clinic",
      "physiotherapist",
    ],
    weak: [
      "fysioterapi",
      "sjukgymnast",
      "rehab",
      "behandling",
      "logoped",
      "dietist",
      "physiotherapy",
    ],
  },
  therapist: {
    strong: [
      "psykolog",
      "psykoterapeut",
      "samtalsterapeut",
      "psykoterapi",
      "samtalsterapi",
      "terapeut",
      "therapist",
      "psychologist",
      "psychotherapy",
    ],
    weak: [
      "terapi",
      "kbt",
      "parterapi",
      "somatisk",
      "somatic",
      "trauma",
      "counselling",
      "counseling",
      "mindfulness",
    ],
  },
  salon: {
    strong: [
      "frisör",
      "frisörsalong",
      "salong",
      "barber",
      "barbershop",
      "hairdresser",
      "hair salon",
      "skönhetssalong",
    ],
    weak: [
      "klippning",
      "färgning",
      "slingor",
      "nagelvård",
      "naglar",
      "hudvård",
      "fransar",
      "makeup",
      "beauty",
    ],
  },
  cleaning: {
    strong: [
      "städ",
      "städning",
      "städfirma",
      "städbolag",
      "cleaning",
      "cleaners",
      "cleaning service",
    ],
    weak: [
      "flyttstäd",
      "hemstäd",
      "kontorsstäd",
      "storstäd",
      "fönsterputs",
      "byggstäd",
      "trappstäd",
    ],
  },
  restaurant: {
    strong: [
      "restaurang",
      "restaurant",
      "bistro",
      "pizzeria",
      "krog",
      "café",
      "cafe",
    ],
    weak: [
      "meny",
      "menu",
      "matsedel",
      "lunch",
      "middag",
      "catering",
      "sushi",
      "à la carte",
      "dagens rätt",
    ],
  },
  fitness: {
    strong: [
      "gym",
      "fitness",
      "crossfit",
      "träningscenter",
      "gymkedja",
    ],
    weak: [
      "träning",
      "yoga",
      "pilates",
      "personlig tränare",
      "personal trainer",
      "pass",
      "workout",
      "spinning",
    ],
  },
  animals: {
    strong: [
      "hundtrim",
      "hundtrimning",
      "hundfrisör",
      "hundsalong",
      "hunddagis",
      "hundpensionat",
      "kattpensionat",
      "trimsalong",
      "dog grooming",
      "pet grooming",
      "dog day care",
      "salon dla psów",
    ],
    weak: ["hund", "husdjur", "päls", "ras", "dog", "pet", "grooming", "pies"],
  },
  retail: {
    strong: [
      "blomsterbutik",
      "blomsteraffär",
      "blomsterhandel",
      "kwiaciarnia",
      "presentbutik",
      "inredningsbutik",
      "klädbutik",
      "leksaksbutik",
      "bokhandel",
      "järnhandel",
      "gårdsbutik",
      "flower shop",
      "gift shop",
      "local shop",
    ],
    weak: ["butik", "florist", "sortiment", "loppis", "second hand", "shop", "sklep", "boutique"],
  },
  hotel: {
    strong: [
      "hotell",
      "pensionat",
      "vandrarhem",
      "gästgiveri",
      "gästhus",
      "stuguthyrning",
      "stugby",
      "bed and breakfast",
      "bed & breakfast",
      "guesthouse",
      "pensjonat",
      "noclegi",
    ],
    weak: [
      "boende",
      "logi",
      "rum",
      "frukost",
      "övernattning",
      "hostel",
      "hotel",
      "nocleg",
    ],
  },
  school: {
    strong: [
      "trafikskola",
      "körskola",
      "driving school",
      "szkoła jazdy",
      "musikskola",
      "språkskola",
      "dansskola",
      "ridskola",
      "kursgård",
      "folkhögskola",
      "yrkeshögskola",
      "language school",
    ],
    weak: [
      "körkort",
      "körlektion",
      "riskutbildning",
      "handledarkurs",
      "intensivkurs",
      "utbildning",
      "kurser",
      "elev",
      "lektion",
      "lesson",
      "course",
      "tutoring",
    ],
  },
  autoshop: {
    strong: [
      "bilverkstad",
      "bilservice",
      "bilreparation",
      "bilmekaniker",
      "fordonsverkstad",
      "däckverkstad",
      "däckhotell",
      "car repair",
      "auto repair",
      "car mechanic",
      "warsztat samochodowy",
    ],
    weak: ["mekaniker", "hjulinställning", "kamrem", "bilbesiktning", "tyre", "opony"],
  },
  handyman: {
    strong: [
      "snickare",
      "byggfirma",
      "hantverkare",
      "hantverk",
      "elektriker",
      "rörmokare",
      "handyman",
      "builder",
      "carpenter",
      "plumber",
      "electrician",
    ],
    weak: [
      "bygg",
      "renovering",
      "målare",
      "plattsättare",
      "takläggare",
      "badrumsrenovering",
      "altan",
      "snickeri",
    ],
  },
  consultant: {
    strong: [
      "konsult",
      "rådgivare",
      "consultant",
      "consulting",
      "managementkonsult",
      "redovisningskonsult",
    ],
    weak: [
      "rådgivning",
      "strategi",
      "affärsutveckling",
      "projektledning",
      "advisory",
      "förstudie",
    ],
  },
  coach: {
    strong: [
      "coach",
      "coaching",
      "livscoach",
      "hälsocoach",
      "karriärcoach",
    ],
    weak: [
      "mentor",
      "mentorskap",
      "ledarskap",
      "grupprogram",
      "förändring",
    ],
  },
  freelancer: {
    strong: [
      "frilans",
      "frilansare",
      "freelance",
      "freelancer",
    ],
    weak: [
      "egenföretagare",
      "fotograf",
      "copywriter",
      "skribent",
      "illustratör",
      "webbutvecklare",
      "formgivare",
    ],
  },
};

/** Substring match that respects word edges across Unicode letters (so "bar"
 *  does not match inside "barn", and Swedish å/ä/ö count as letters - JS `\b`
 *  treats them as boundaries without the /u flag, which would misfire). */
export function textHas(haystack: string, term: string): boolean {
  if (!term) return false;
  const t = term.toLowerCase();
  const esc = t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  // Non-capturing, single-char edges - linear scan, no nested quantifiers (no
  // catastrophic backtracking). Matches the term only at word boundaries.
  return new RegExp(`(?:^|[^\\p{L}])${esc}(?:[^\\p{L}]|$)`, "iu").test(haystack);
}

/** Swedish/English inflection endings a keyword may carry. Without these,
 *  "klinik" failed on a page that only ever writes "kliniken"/"kliniker" —
 *  which is most of them. Bounded alternation, matched only at a word end. */
const INFLECTIONS =
  "(?:s|n|t|e|en|et|er|ar|or|na|ns|ts|es|ers|ens|ets|ors|are|aren|arna|erna|orna)?";

/** How a keyword turned up in the page text.
 *  - `exact`     the word itself, possibly inflected ("klinik", "kliniken")
 *  - `compound`  the tail of a longer Swedish compound ("allmäntandvård")
 *  - `null`      absent */
export type TermMatch = "exact" | "compound" | null;

/** Match a keyword against page text, tolerating Swedish morphology.
 *
 *  Swedish builds compounds head-last, so a dental clinic writes
 *  "allmäntandvård" and "tandvårdsklinik" and never the bare "tandvård" — the
 *  strict word-boundary rule scored those pages zero and they all imported as
 *  "generic". A compound hit is reported separately because it is a weaker
 *  signal than the standalone word and the caller scores it lower. */
export function matchTerm(haystack: string, term: string): TermMatch {
  if (!term) return null;
  const esc = term.toLowerCase().replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  if (new RegExp(`(?:^|[^\\p{L}])${esc}${INFLECTIONS}(?:[^\\p{L}]|$)`, "iu").test(haystack)) {
    return "exact";
  }
  // Compound tail: at least two letters of a preceding stem, then the term at a
  // word end. Multi-word terms ("hair salon") are never compounded, so skip.
  if (/\s/.test(term)) return null;
  if (new RegExp(`\\p{L}{2,}${esc}${INFLECTIONS}(?:[^\\p{L}]|$)`, "iu").test(haystack)) {
    return "compound";
  }
  return null;
}

export type VerticalGuess = {
  vertical: Vertical;
  /** True only when the top signal is strong and clearly beats the runner-up. */
  confident: boolean;
  /** Per-vertical scores, exposed for tests/debugging. */
  scores: Record<Trade, number>;
  /** The best few candidates, best first, `vertical` always at index 0.
   *  The import UI offers these instead of a single pre-selected guess: the
   *  runners-up are already computed, and one tap to correct the industry beats
   *  hunting for it in a 13-item dropdown later. Only trades with real evidence
   *  are listed, so a page with no signal offers nothing to choose from. */
  alternatives: Vertical[];
};

/** How many candidates the UI may offer. */
const MAX_ALTERNATIVES = 3;

/** Classify a page into one of the business verticals. Inputs are the already-
 *  extracted fields plus the page text; everything is matched case-insensitively
 *  with word-edge boundaries. */
export function classifyVertical(input: {
  name?: string;
  description?: string;
  services?: string[];
  text?: string;
  url?: string;
}): VerticalGuess {
  // Name + description + services weigh as much as the body text; we lowercase
  // the whole haystack once. The URL host can carry the trade too (e.g.
  // "stadfirman.se") so it's folded in.
  const haystack = [
    input.name ?? "",
    input.description ?? "",
    (input.services ?? []).join(" "),
    input.text ?? "",
    (input.url ?? "").replace(/[/.]/g, " "),
  ]
    .join(" ")
    .toLowerCase();

  const scores = {} as Record<Trade, number>;
  const strongHits = {} as Record<Trade, number>;
  // Distinct keywords matched, regardless of weight. Breadth of evidence is the
  // first tie-break: three converging dental services beat the single generic
  // word "klinik", which a dentist, a physio and a skin clinic all use.
  const termHits = {} as Record<Trade, number>;
  // Declaration order of KEYWORDS runs specific -> generic; it is the final,
  // deterministic tie-break so the same page never flips between runs.
  const specificity = Object.fromEntries(
    (Object.keys(KEYWORDS) as Trade[]).map((k, i) => [k, i]),
  ) as Record<Trade, number>;
  (Object.keys(KEYWORDS) as Trade[]).forEach((tradeKey) => {
    const { strong, weak } = KEYWORDS[tradeKey];
    let score = 0;
    let strongCount = 0;
    let termCount = 0;
    for (const term of strong) {
      const hit = matchTerm(haystack, term);
      if (hit) termCount += 1;
      if (hit === "exact") {
        score += 3;
        strongCount += 1;
      } else if (hit === "compound") {
        // "allmäntandvård" really is a dentist signal, but a compound is easier
        // to hit by accident than the bare word, so it scores like a weak term
        // and never satisfies the "the page names this trade" confidence gate.
        score += 1;
      }
    }
    // Weak terms are ordinary service words; only a standalone match counts,
    // because a compound-tail rule on those is almost all noise.
    for (const term of weak) {
      if (matchTerm(haystack, term) === "exact") {
        score += 1;
        termCount += 1;
      }
    }
    scores[tradeKey] = score;
    strongHits[tradeKey] = strongCount;
    termHits[tradeKey] = termCount;
  });

  const ranked = (Object.keys(scores) as Trade[])
    .map((k) => ({ key: k, score: scores[k] }))
    // Score, then breadth of evidence, then "the page actually names this
    // trade", then specificity — every step deterministic.
    .sort(
      (a, b) =>
        b.score - a.score ||
        termHits[b.key] - termHits[a.key] ||
        strongHits[b.key] - strongHits[a.key] ||
        specificity[a.key] - specificity[b.key],
    );

  const top = ranked[0];
  const second = ranked[1];

  // Candidates the UI may offer as a correction. Only trades that scored at
  // all - offering a zero-evidence trade as a "suggestion" is noise.
  const alternativesFrom = (winner: Vertical): Vertical[] => {
    const rest = ranked
      .filter((r) => r.score > 0 && r.key !== winner)
      .slice(0, MAX_ALTERNATIVES - 1)
      .map((r) => r.key as Vertical);
    return [winner, ...rest];
  };

  if (!top || top.score === 0) {
    return { vertical: "generic", confident: false, scores, alternatives: ["generic"] };
  }

  // Robustness against false positives: a SINGLE incidental weak keyword
  // ("beauty", "lunch", "behandling") must not pick a specific vertical - that
  // was the dominant misfire. Emit a trade only when the page actually names it
  // (a strong match) OR at least two weak signals converge on the SAME trade
  // (score ≥ 2). Otherwise fall back to "generic" - a wrong specific guess is
  // worse than the safe default. (Reported: scrape sometimes locked the wrong
  // industry.)
  const topHadStrong = strongHits[top.key] > 0;
  const emitSpecific = topHadStrong || top.score >= 2;
  if (!emitSpecific) {
    // The weak signal is still worth OFFERING even when it is too thin to
    // pre-select: "generic" wins, the near-misses ride along as one-tap fixes.
    return {
      vertical: "generic",
      confident: false,
      scores,
      alternatives: alternativesFrom("generic"),
    };
  }

  // Confident = a real trade name matched AND it clears the runner-up by a
  // margin. Otherwise keep the guess but flag it soft so the UI invites a fix.
  const confident = topHadStrong && top.score - (second?.score ?? 0) >= 2;
  return {
    vertical: top.key,
    confident,
    scores,
    alternatives: alternativesFrom(top.key),
  };
}
