// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/scrape/classifyPlatform.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

// ---------------------------------------------------------------------------
// Best-guess "which website builder is this site on?" from the scraped HTML +
// URL. Pure + dependency-free so it runs inside the Convex `scrapeSite` action
// and is unit-testable. Best-effort and additive: it only tailors the import
// preview ("what we couldn't move") and links to the right /migrate guide - it
// never blocks an import. Unknown / no signal → "other".
//
// This enum is the BUILDER axis only. "Does this site run a store?" is a
// separate question with a separate answer - a WordPress site on WooCommerce is
// both, and folding "woocommerce" in here would force a choice between two true
// answers - so store detection lives in `detectCommerce.ts` and is additive.
// ---------------------------------------------------------------------------

export type PlatformId =
  | "wix"
  | "squarespace"
  | "wordpress"
  | "webflow"
  | "framer"
  | "shopify"
  | "durable"
  | "one_com"
  | "loopia"
  | "hemsida24"
  | "other";

export type PlatformGuess = {
  platform: PlatformId;
  /** True when a strong, builder-specific signature matched (vs a soft mention). */
  confident: boolean;
};

// Ordered most-specific-first. A WordPress site hosted at Loopia keeps its own
// domain and `/wp-content/` markers (and won't carry the "Loopia Sitebuilder"
// string), so WordPress's strong markers still win - Loopia's own builder is
// matched by its distinct strings/host.
const SIGNATURES: { id: PlatformId; strong: RegExp[]; weak: RegExp[] }[] = [
  {
    id: "wix",
    strong: [/generator"[^>]*content="wix/i, /static\.wixstatic\.com/i, /\.parastorage\.com/i],
    weak: [/\bwix\.com\b/i],
  },
  {
    id: "squarespace",
    strong: [
      /this is squarespace/i,
      /static1\.squarespace\.com/i,
      /generator"[^>]*content="squarespace/i,
      /\.sqsp\.net/i,
    ],
    weak: [/\bsquarespace\.com\b/i],
  },
  {
    // Webflow stamps every page with these two attributes and ships webflow.js
    // for its interactions. `w-` utility classes alone are too weak - templates
    // copied out of Webflow carry them long after leaving.
    id: "webflow",
    strong: [
      /\bdata-wf-(?:page|site)=/i,
      /(?:^|[/"'])js\/webflow(?:\.min)?\.js/i,
      /assets(?:-global)?\.website-files\.com/i,
      /uploads-ssl\.webflow\.com/i,
    ],
    weak: [/\bwebflow\.(?:com|io)\b/i],
  },
  {
    // Framer serves its runtime and images off its own hosts and marks the root
    // node. There is no export to check against - a Framer site is only ever
    // read live, which is why naming it matters for the "we need to read this a
    // different way" path.
    id: "framer",
    strong: [
      /framerusercontent\.com/i,
      /\bid="__framer-badge/i,
      /generator"[^>]*content="framer/i,
      /events\.framer\.com/i,
    ],
    weak: [/\bframer\.(?:com|website|app)\b/i],
  },
  {
    // A store, and named as the builder because the storefront IS the site. What
    // it sells is still `detectCommerce`'s answer, not this one.
    id: "shopify",
    strong: [
      /cdn\.shopify\.com/i,
      /Shopify\.theme\s*=/i,
      /\bshopify-(?:section|block)\b/i,
      /myshopify\.com/i,
    ],
    weak: [/\bshopify\b/i],
  },
  {
    id: "durable",
    strong: [/generator"[^>]*content="durable/i, /\bdurable\.co\b/i],
    weak: [],
  },
  {
    id: "hemsida24",
    strong: [/hemsida24/i],
    weak: [],
  },
  {
    id: "one_com",
    strong: [
      /generator"[^>]*content="one\.com/i,
      /skapad med one\.com/i,
      /created with one\.com/i,
      /one\.com\/websitebuilder/i,
    ],
    weak: [/\bone\.com\b/i],
  },
  {
    id: "loopia",
    strong: [/loopia sitebuilder/i, /\.loopia\.(se|com)/i],
    weak: [/\bloopia\b/i],
  },
  {
    id: "wordpress",
    strong: [/\/wp-content\//i, /\/wp-json/i, /wp-includes/i, /generator"[^>]*content="wordpress/i],
    weak: [],
  },
];

/** Classify a scraped page into a known builder. `url` is folded in so a host
 *  like `*.loopia.se` or `*.wixsite.com` counts toward the guess. */
export function classifyPlatform(html: string, url?: string): PlatformGuess {
  const haystack = `${html ?? ""} ${url ?? ""}`;
  let weakHit: PlatformId | null = null;

  for (const sig of SIGNATURES) {
    if (sig.strong.some((re) => re.test(haystack))) {
      return { platform: sig.id, confident: true };
    }
    if (!weakHit && sig.weak.some((re) => re.test(haystack))) {
      weakHit = sig.id;
    }
  }

  if (weakHit) return { platform: weakHit, confident: false };
  return { platform: "other", confident: false };
}

/** Human-facing brand label for a platform (not translated). */
export const PLATFORM_LABELS: Record<PlatformId, string> = {
  wix: "Wix",
  squarespace: "Squarespace",
  wordpress: "WordPress",
  webflow: "Webflow",
  framer: "Framer",
  shopify: "Shopify",
  durable: "Durable",
  one_com: "one.com",
  loopia: "Loopia",
  hemsida24: "Hemsida24",
  other: "",
};

/** Map a detected platform to a published /migrate/[slug] guide, if one exists.
 *  Squarespace/WordPress are backlog (no page yet) → undefined. */
export function competitorSlugForPlatform(platform: PlatformId): string | undefined {
  switch (platform) {
    case "wix":
      return "wix";
    case "one_com":
      return "one-com";
    case "loopia":
      return "loopia";
    case "hemsida24":
      return "hemsida24";
    case "squarespace":
      return "squarespace";
    case "wordpress":
      return "wordpress";
    case "webflow":
      return "webflow";
    case "framer":
      return "framer";
    case "shopify":
      return "shopify";
    case "durable":
      return "durable";
    default:
      return undefined;
  }
}
