// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/scrape/detectCommerce.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

// ---------------------------------------------------------------------------
// "Does this site already sell things?" - detection only.
//
// Deliberately a SEPARATE axis from classifyPlatform.ts: that file answers
// "which website BUILDER is this" (Wix / WordPress / Loopia), this one answers
// "is there a STORE on it". A WordPress site running WooCommerce is both at the
// same time, so one enum cannot express the pair - extending `PlatformId` with
// "woocommerce" would have forced a choice between the two true answers. They
// stay independent, and a detected store is an additive finding on top of
// whatever builder was guessed.
//
// This module NEVER activates anything. It connects no provider, imports no
// product, enables no payment and rewrites no checkout link. Its only output is
// a reviewable finding for the owner (the "store_detected" import action).
//
// THE RULE - no single signal is safe on its own, so we require TWO of three,
// at least one of them transactional:
//   1. a store-platform fingerprint in the markup (Shopify / WooCommerce /
//      Ecwid / Wix Stores / Squarespace Commerce)
//   2. a reachable cart or checkout URL on the same host          (transactional)
//   3. >= 3 distinct JSON-LD `Product` nodes whose offer carries BOTH a price
//      and an availability                                         (transactional)
// Structured data alone is never enough: a product-review blog marks up
// products it does not sell, and a restaurant menu or a service price list is
// full of prices with nothing to buy.
//
// Pure: no network, no DOM, no state. Callers pass already-fetched HTML.
// ---------------------------------------------------------------------------

import { jsonLdBlocks } from "../external/localBusiness";
import { safeDecodeURIComponent } from "../net/url";

/** A store platform we can name. "unknown" = the transactional signals fired
 *  but no vendor fingerprint did, so we know they sell, not what they sell on. */
export type StoreProvider =
  | "shopify"
  | "woocommerce"
  | "ecwid"
  | "wix"
  | "squarespace"
  | "unknown";

export type CommerceSignals = {
  /** A vendor-specific string was in the markup. Not transactional on its own:
   *  plenty of WordPress themes ship WooCommerce assets with no shop. */
  platformFingerprint: boolean;
  /** A cart/checkout URL on the same host. Transactional. */
  cartUrl: boolean;
  /** >= 3 distinct JSON-LD products with price + availability. Transactional. */
  pricedCatalog: boolean;
};

export type CommerceDetection = {
  provider: StoreProvider;
  /** "high" = we can name the provider. "low" = the site clearly sells, but we
   *  could not tell on what, so the owner has to confirm before anyone acts. */
  confidence: "high" | "low";
  signals: CommerceSignals;
  /** The concrete strings we actually saw (fingerprints, cart links, product
   *  names), so no downstream label has to hedge. Bounded. */
  evidence: string[];
  /** "At least this many" - never exact. Counted from priced JSON-LD products
   *  and product-detail URLs on the pages we read; a store's full catalogue is
   *  behind pagination we never crawl. null when we saw no countable product. */
  productCountEstimate: number | null;
  cartUrls: string[];
};

/** Human-facing brand label for a store platform (not translated). Empty for
 *  "unknown" - a finding we cannot name must not print one. */
export const STORE_PROVIDER_LABELS: Record<StoreProvider, string> = {
  shopify: "Shopify",
  woocommerce: "WooCommerce",
  ecwid: "Ecwid",
  wix: "Wix Stores",
  squarespace: "Squarespace Commerce",
  unknown: "",
};

/** Below this a `Product` block is markup, not a catalogue: one or two priced
 *  products is what a review post or a single-item landing page carries. */
const MIN_PRODUCTS = 3;

const MAX_EVIDENCE = 8;
const MAX_CART_URLS = 5;

/** Most-specific first. Each token is a string only that vendor's storefront
 *  emits; the matched text goes into `evidence` verbatim. */
const PROVIDER_FINGERPRINTS: Array<{
  id: Exclude<StoreProvider, "unknown">;
  markers: RegExp[];
}> = [
  {
    id: "shopify",
    markers: [/cdn\.shopify\.com/i, /[\w-]+\.myshopify\.com/i, /Shopify\.theme/, /\/cdn\/shop\//i],
  },
  {
    id: "woocommerce",
    markers: [/wp-content\/plugins\/woocommerce/i, /woocommerce-page/i, /wc-ajax/i],
  },
  { id: "ecwid", markers: [/ecwid\.com/i, /\bec-store\b/i, /ecwid_script/i] },
  { id: "wix", markers: [/wixstores/i] },
  { id: "squarespace", markers: [/\/api\/commerce\//i] },
];

/** Whole path segments that mean "this link goes to a basket or a checkout",
 *  sv + en + pl. Matched as complete segments so `/kassaskap` (a safe-cabinet
 *  seller's product page) is not read as a checkout. */
const CART_SEGMENTS = new Set([
  "cart",
  "carts",
  "checkout",
  "checkouts",
  "basket",
  "varukorg",
  "varukorgen",
  "kundvagn",
  "kundvagnen",
  "kassa",
  "kassan",
  "koszyk",
  "zamowienie",
]);

/** WooCommerce puts the whole add-to-cart action in the query string, so a shop
 *  can be obvious without a single `/cart` href. */
const ADD_TO_CART_RE = /[?&]add-to-cart=/i;

/** Shopify (`/products/<slug>`) and WooCommerce (`/product/<slug>`) product
 *  detail URLs, plus the Swedish equivalents builders localise to. Generic
 *  `/shop/` and `/butik/` are left out: those are category pages. */
const PRODUCT_URL_RE = /\/(?:products?|produkt(?:er)?)\/[a-z0-9][^"'\s?#<>]*/gi;

const JSONLD_PRODUCT_TYPES = new Set(["product", "individualproduct", "productmodel"]);

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function safeUrl(raw: string, base?: URL): URL | null {
  try {
    return new URL(raw, base);
  } catch {
    return null;
  }
}

/** The vendor whose fingerprint matched, plus the strings that matched it. */
function matchProvider(html: string): {
  provider: Exclude<StoreProvider, "unknown"> | null;
  evidence: string[];
} {
  for (const fp of PROVIDER_FINGERPRINTS) {
    const hits = fp.markers.map((re) => html.match(re)?.[0]).filter((m): m is string => !!m);
    if (hits.length > 0) return { provider: fp.id, evidence: [...new Set(hits)] };
  }
  return { provider: null, evidence: [] };
}

/** Resolve one href/action against the page, keeping only same-host links.
 *  Without a `baseUrl` we can still trust relative links (same host by
 *  construction) and must reject absolute ones - which is what keeps a lone
 *  Etsy or Tradera link from reading as this site's own checkout. */
function resolveSameHost(
  raw: string,
  base: URL | null,
): { href: string; pathname: string; search: string } | null {
  if (!raw || /^(mailto:|tel:|javascript:|data:|#)/i.test(raw)) return null;
  const isAbsolute = /^[a-z][a-z0-9+.-]*:/i.test(raw) || raw.startsWith("//");
  if (isAbsolute) {
    if (!base) return null;
    const abs = safeUrl(raw, base);
    if (!abs || abs.hostname !== base.hostname) return null;
    return { href: abs.href, pathname: abs.pathname, search: abs.search };
  }
  // Relative: resolve against the page when we have it, otherwise against a
  // throwaway origin purely to read the path - the href we report stays the
  // one the page actually wrote.
  const rel = safeUrl(raw, base ?? new URL("https://relative.invalid/"));
  if (!rel) return null;
  return { href: base ? rel.href : raw, pathname: rel.pathname, search: rel.search };
}

function isCartPath(pathname: string): boolean {
  return pathname
    .split("/")
    .filter(Boolean)
    .some((seg) => CART_SEGMENTS.has(safeDecodeURIComponent(seg).toLowerCase()));
}

/** Same-host cart/checkout targets, from links and form actions. Deduped and
 *  bounded; we only ever COUNT these - the crawl still never follows them. */
function findCartUrls(html: string, baseUrl?: string): string[] {
  const base = baseUrl ? safeUrl(baseUrl) : null;
  const out: string[] = [];
  const seen = new Set<string>();
  for (const m of html.matchAll(/(?:href|action)=["']([^"']+)["']/gi)) {
    const target = resolveSameHost(m[1], base);
    if (!target) continue;
    if (!isCartPath(target.pathname) && !ADD_TO_CART_RE.test(target.search)) continue;
    const key = target.href.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(target.href);
    if (out.length >= MAX_CART_URLS) break;
  }
  return out;
}

function typesOf(node: Record<string, unknown>): string[] {
  const t = node["@type"];
  return (Array.isArray(t) ? t : [t])
    .filter((x): x is string => typeof x === "string")
    .map((x) => x.toLowerCase());
}

/** Every offer hanging off a product, including the ones nested inside an
 *  AggregateOffer. */
function offersOf(node: Record<string, unknown>): Record<string, unknown>[] {
  const raw = node.offers;
  const list = (Array.isArray(raw) ? raw : [raw]).filter(isRecord);
  const out: Record<string, unknown>[] = [];
  for (const offer of list) {
    out.push(offer);
    const nested = offer.offers;
    out.push(...(Array.isArray(nested) ? nested : [nested]).filter(isRecord));
  }
  return out;
}

function hasValue(v: unknown): boolean {
  if (typeof v === "number") return Number.isFinite(v);
  return typeof v === "string" && v.trim() !== "";
}

/** A sellable offer states BOTH what it costs and whether it is in stock. The
 *  availability half is what separates a shop from a review site: a blog that
 *  marks up the camera it reviewed lists a price and stops there. */
function isSellableOffer(offer: Record<string, unknown>): boolean {
  const priced = hasValue(offer.price) || hasValue(offer.lowPrice) || hasValue(offer.highPrice);
  return priced && hasValue(offer.availability);
}

/** Distinct products whose offer is sellable, with their names for evidence. */
function pricedProducts(html: string): { count: number; names: string[] } {
  const seen = new Set<string>();
  const names: string[] = [];
  jsonLdBlocks(html).forEach((node, i) => {
    if (!typesOf(node).some((t) => JSONLD_PRODUCT_TYPES.has(t))) return;
    if (!offersOf(node).some(isSellableOffer)) return;
    const name = typeof node.name === "string" ? node.name.trim() : "";
    const key = (
      name ||
      (typeof node.sku === "string" && node.sku) ||
      (typeof node.url === "string" && node.url) ||
      (typeof node["@id"] === "string" && node["@id"]) ||
      `#${i}`
    )
      .toString()
      .toLowerCase();
    if (seen.has(key)) return;
    seen.add(key);
    if (name) names.push(name.slice(0, 60));
  });
  return { count: seen.size, names };
}

/** Distinct product-detail URLs linked from the page. A lower bound on the
 *  catalogue, used only to put a number in front of the owner. */
function countProductUrls(html: string): number {
  const seen = new Set<string>();
  for (const m of html.matchAll(PRODUCT_URL_RE)) {
    seen.add(m[0].toLowerCase().replace(/\/$/, ""));
  }
  return seen.size;
}

/**
 * Look at one already-fetched page and decide whether the owner is already
 * selling on it. Returns null - not a low-confidence guess - when the two-of-
 * three rule is not met, because "we found nothing" is the honest answer and a
 * hedged finding would still put a decision in front of the owner.
 *
 * `baseUrl` is optional: without it, only relative cart links count (an
 * absolute link could point at someone else's shop).
 */
export function detectCommerce(input: {
  html: string;
  baseUrl?: string;
}): CommerceDetection | null {
  const html = input.html ?? "";
  if (!html) return null;

  const { provider, evidence: platformEvidence } = matchProvider(html);
  const cartUrls = findCartUrls(html, input.baseUrl);
  const catalog = pricedProducts(html);

  const signals: CommerceSignals = {
    platformFingerprint: platformEvidence.length > 0,
    cartUrl: cartUrls.length > 0,
    pricedCatalog: catalog.count >= MIN_PRODUCTS,
  };

  const hits = Object.values(signals).filter(Boolean).length;
  const transactional = signals.cartUrl || signals.pricedCatalog;
  // Two of three AND at least one transactional. The second half is redundant
  // while there are exactly three signals, and stays explicit so that adding a
  // fourth non-transactional fingerprint later cannot quietly weaken the rule.
  if (hits < 2 || !transactional) return null;

  const productCountEstimate = Math.max(catalog.count, countProductUrls(html)) || null;

  const evidence = [...platformEvidence, ...cartUrls, ...catalog.names].slice(0, MAX_EVIDENCE);

  return {
    provider: provider ?? "unknown",
    // Naming the provider is what lets the follow-up say "connect the store you
    // already have" instead of asking the owner what they want. Without a
    // vendor we only know that money changes hands somewhere.
    confidence: provider ? "high" : "low",
    signals,
    evidence,
    productCountEstimate,
    cartUrls,
  };
}

/**
 * Combine two pages' findings for a crawl (home page + subpages). Keeps the
 * stronger one and unions its cart links and evidence. Note the honest limit:
 * a page that failed the two-of-three rule returned null, so its lone signal is
 * not carried forward - detection is per page, never assembled across pages.
 */
export function mergeCommerceDetections(
  a: CommerceDetection | null | undefined,
  b: CommerceDetection | null | undefined,
): CommerceDetection | null {
  if (!a) return b ?? null;
  if (!b) return a;
  const score = (d: CommerceDetection) =>
    Object.values(d.signals).filter(Boolean).length + (d.confidence === "high" ? 1 : 0);
  const [primary, other] = score(b) > score(a) ? [b, a] : [a, b];
  return {
    ...primary,
    evidence: [...new Set([...primary.evidence, ...other.evidence])].slice(0, MAX_EVIDENCE),
    cartUrls: [...new Set([...primary.cartUrls, ...other.cartUrls])].slice(0, MAX_CART_URLS),
    productCountEstimate:
      primary.productCountEstimate === null && other.productCountEstimate === null
        ? null
        : Math.max(primary.productCountEstimate ?? 0, other.productCountEstimate ?? 0),
  };
}
