// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/scrape/jsonLdHours.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

// ---------------------------------------------------------------------------
// schema.org `openingHoursSpecification` -> the weekly rows an opening-hours
// section needs.
//
// A Bokadirekt profile page carries a LocalBusiness JSON-LD node with the
// owner's real weekly hours, and we read the name and address out of that same
// node already - but skipped the hours entirely, so a salon that imported from
// Bokadirekt got a site with no opening hours at all and had to retype them
// (backlog 0277). Every ordinary small-business site with the standard markup
// gets this for free too; nothing here is Bokadirekt-specific.
//
// A weekday listed TWICE (lunch and dinner service) collapses to one span plus
// the break between them via `spanWithBreaks`, which is how `openingDay` stores
// a split day (backlog 0989).
//
// Pure (no DOM, no network) so it is unit-testable, like the rest of lib/scrape.
// ---------------------------------------------------------------------------

import { spanWithBreaks } from "../sections/openingHours";

export type Weekday = "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";

export type ScrapedHours = Array<{
  day: Weekday;
  open: string;
  close: string;
  breaks?: Array<{ start: string; end: string }>;
}>;

const WEEK: Weekday[] = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"];

const DAY_NAMES: Record<string, Weekday> = {
  monday: "mon",
  tuesday: "tue",
  wednesday: "wed",
  thursday: "thu",
  friday: "fri",
  saturday: "sat",
  sunday: "sun",
};

/** `dayOfWeek` is a day name, but real pages emit it as a bare name
 *  ("Monday"), a full schema.org URL ("https://schema.org/Monday") or an
 *  abbreviation ("Mo"), in any case. Anything else is skipped rather than
 *  guessed at. */
function toWeekday(value: unknown): Weekday | null {
  if (typeof value !== "string") return null;
  const name = value.trim().toLowerCase().split("/").pop() ?? "";
  if (DAY_NAMES[name]) return DAY_NAMES[name];
  // Abbreviations ("Mo", "Tue", …). Two letters is the shortest unambiguous
  // prefix across the week ("t" and "s" each match two days).
  if (name.length < 2) return null;
  const full = Object.keys(DAY_NAMES).find((d) => d.startsWith(name));
  return full ? DAY_NAMES[full] : null;
}

/** "09:00", "09:00:00" and "9:00" all mean the same thing; anything that is not
 *  a time is rejected so a malformed listing cannot produce a nonsense row. */
function toHhmm(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const m = value.trim().match(/^(\d{1,2}):(\d{2})/);
  if (!m) return null;
  const h = Number(m[1]);
  const min = Number(m[2]);
  if (h > 23 || min > 59) return null;
  return `${String(h).padStart(2, "0")}:${String(min).padStart(2, "0")}`;
}

export type JsonLdHours = {
  /** The weekdays we understood, Monday-first. */
  hours: ScrapedHours;
  /** Day names the listing gave that we could NOT map to a weekday, verbatim.
   *  Deduped, bounded, each clamped — this is untrusted text off someone
   *  else's page and it ends up rendered in the import preview. */
  unreadableDays: string[];
};

/** Read the weekly hours off one JSON-LD node (a LocalBusiness or similar).
 *  Returns undefined when the node carries no specification at all.
 *
 *  A spec entry with `opens === closes` is schema.org's way of saying "closed
 *  all day", and a day with no entry at all is closed too - both simply produce
 *  no row, which the section renders as "Stängt".
 *
 *  Anything we cannot read comes back in `unreadableDays` instead of vanishing.
 *  schema.org's `DayOfWeek` is an enumeration of English names / schema.org
 *  URLs, so a spec-compliant page never populates it - but a page that writes
 *  "Måndag" would otherwise have lost that day with no trace, and an import
 *  that quietly discards a day the owner is open is exactly the kind of silent
 *  loss this codebase keeps having to dig back out (backlog 0277). */
export function hoursFromJsonLd(node: unknown): JsonLdHours | undefined {
  if (!node || typeof node !== "object") return undefined;
  const raw = (node as Record<string, unknown>).openingHoursSpecification;
  const specs = Array.isArray(raw) ? raw : raw ? [raw] : [];
  if (specs.length === 0) return undefined;

  const byDay = new Map<Weekday, { open: string; close: string }[]>();
  const unreadable = new Set<string>();
  for (const spec of specs) {
    if (!spec || typeof spec !== "object") continue;
    const s = spec as Record<string, unknown>;
    const open = toHhmm(s.opens);
    const close = toHhmm(s.closes);
    // `opens === closes` is schema.org for "closed all day" - a real answer, not
    // a failure to read, so it is never reported.
    if (open && close && open === close) continue;
    const daysRaw = Array.isArray(s.dayOfWeek) ? s.dayOfWeek : [s.dayOfWeek];
    for (const d of daysRaw) {
      const day = toWeekday(d);
      // Report the day whether it was the NAME we could not map ("Måndag") or
      // the TIMES on a day we did recognise (`opens: "nope"`). Both discard a
      // day the owner is open, and from the owner's side they are the same
      // problem: a day that was on their old site is not on their new one.
      // (Checking `open`/`close` here rather than via a boolean also narrows
      // them to `string` for the push below, so no non-null assertion.)
      if (!day || !open || !close) {
        if (typeof d === "string" && d.trim()) {
          unreadable.add(d.trim().slice(0, 40));
        }
        continue;
      }
      const list = byDay.get(day);
      if (list) list.push({ open, close });
      else byDay.set(day, [{ open, close }]);
    }
  }

  // Monday-first, so the rows arrive in the order the site renders them.
  const hours: ScrapedHours = [];
  for (const day of WEEK) {
    const periods = byDay.get(day);
    if (!periods) continue;
    const span = spanWithBreaks(periods);
    if (span) hours.push({ day, ...span });
  }
  const unreadableDays = [...unreadable].slice(0, 7);
  if (hours.length === 0 && unreadableDays.length === 0) return undefined;
  return { hours, unreadableDays };
}
