// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/import/imageCandidates.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

import { decodeHtmlEntities } from "../html/entities";

// ---------------------------------------------------------------------------
// Everything a source page shows as a picture, with enough context around each
// one to decide what it IS. Pure + regex-only (no DOM) so it runs inside a
// Convex action, same constraint as `lib/import/htmlToSections.ts`.
//
// Why this exists: the importer used to read `<img src>` and nothing else, then
// hard-dropped anything whose FILENAME matched `icon|logo|badge|…`, then handed
// the hero whatever was left first in document order. Three failures fell out of
// that, all reported by the owner on a real import (2026-08-07):
//
//   • a modern page hides most of its photography behind `srcset`, `<picture>`
//     and lazy-load `data-src`, so half the pictures were never seen at all;
//   • a certification badge named `iso-9001-2024.png` passes a filename test,
//     and being high in the markup it became the hero;
//   • the source's own `alt` was thrown away and replaced with the business
//     name on every single image.
//
// So: find every picture, keep what the page said about it, and rank rather
// than drop. Nothing here decides the final layout - it produces CANDIDATES.
// `convex/import/imageRoles.ts` may then ask a vision model to re-label them;
// when no model is available `guess` is what the import uses, and it is already
// enough to keep a badge out of the hero.
// ---------------------------------------------------------------------------

/** What a picture is FOR, which is not the same question as where it sits. */
export type ImageRole =
  /** The page's own representative picture. At most one per page. */
  | "hero"
  /** Real photography/artwork: the pool heroes, about and galleries draw from. */
  | "photo"
  /** A brand mark - theirs or a partner's. Belongs in a logo strip, never a hero. */
  | "logo"
  /** A trust badge, certification or award. Same rule as a logo. */
  | "certificate"
  /** A person. Usable as a photo, but team sections want it first. */
  | "portrait"
  /** UI furniture: icons, sprites, spacers, tracking pixels. Never rendered. */
  | "icon"
  /** Texture, pattern, gradient, background wash. Never the subject. */
  | "decor";

/** Roles that may carry a section's media. The rest are furniture. */
export const RENDERABLE_ROLES: ReadonlySet<ImageRole> = new Set<ImageRole>([
  "hero",
  "photo",
  "portrait",
]);

export type ImageCandidate = {
  /** Absolute URL. */
  url: string;
  /** The source's own alt text, decoded. Empty when the page gave none - which
   *  is itself a signal (decorative images are the ones authors leave blank). */
  alt: string;
  /** Order of first appearance in the document, 0-based. */
  index: number;
  /** Byte offset in the source HTML. Comparable with other offsets read off the
   *  same document, which is how the importer keeps a page's own section ORDER
   *  instead of re-sorting everything into a fixed ladder. */
  docOffset: number;
  /** Intrinsic size, only when the markup actually declared it. */
  width?: number;
  height?: number;
  /** Which structural region of the page it sat in. A picture inside <header>
   *  or <footer> is furniture far more often than it is content. */
  region: "header" | "footer" | "nav" | "aside" | "body";
  /** How it was found. A CSS background is rarely a page's subject; an
   *  `og:image` is by definition the page's own pick. */
  source: "img" | "picture" | "lazy" | "background" | "og";
  /** Text of the nearest heading above it, for context in the vision prompt. */
  nearestHeading?: string;
  /** Lowercased tokens from class/id/filename that hint at a role. Kept so the
   *  decision is auditable rather than a black box. */
  hints: string[];
  /** Deterministic role, used as-is when no vision model runs. */
  guess: ImageRole;
};

// --- token vocabularies ----------------------------------------------------
// Matched against the candidate's `hints`, which are class + id + title +
// FILENAME already split into lowercase tokens. The signal moves between those
// by platform: Webflow puts it in the class, WordPress in the filename, a
// hand-built site in the id - so all of them are searched, and the folder path
// deliberately is NOT (a photo under `/assets/logos/2024/` is still a photo).
//
// These are PREFIX matches on a token, not whole-word matches. Swedish inflects
// ("auktoriserad", "trygghet", "medlemskap"), and a whole-word test silently
// missed every one of them - which is how a certification badge stayed
// unclassified and walked into the hero.

const matches = (hints: readonly string[], prefixes: readonly string[]): boolean =>
  hints.some((h) => prefixes.some((p) => h.startsWith(p)));

const LOGO_PREFIXES = [
  "logo",
  "logga",
  "logotyp",
  "brand",
  "wordmark",
  "partner",
  "sponsor",
  "samarbet",
] as const;

/** Swedish trade sites are dense with these. `iso` is deliberately absent - it
 *  is the start of "isolering" (insulation), a real photo subject - and handled
 *  by the standard-number rule below instead. */
const CERT_PREFIXES = [
  "cert",
  "badge",
  "award",
  "utmark",
  "utmärk",
  "diplom",
  "godkand",
  "godkänd",
  "auktoris",
  "behorig",
  "behörig",
  "trygg",
  "garanti",
  "medlem",
  "member",
  "accredit",
  "approved",
  "betyg",
  "swedac",
  "svanen",
  "byggmastar",
  "byggmästar",
  "mastare",
  "mästare",
] as const;

const ICON_PREFIXES = [
  "icon",
  "ikon",
  "sprite",
  "favicon",
  "pixel",
  "spacer",
  "blank",
  "placeholder",
  "arrow",
  "chevron",
  "caret",
  "bullet",
  "divider",
  "separator",
  "loader",
  "spinner",
  "hamburger",
] as const;

const DECOR_PREFIXES = [
  "pattern",
  "texture",
  "gradient",
  "overlay",
  "swirl",
  "noise",
  "grain",
  "deco",
  "ornament",
] as const;

/** Words that mean decoration on a CSS background and mean nothing at all on a
 *  real `<img>`.
 *
 *  A full-bleed cover photo is routinely called a background by the markup
 *  around it — Webflow writes `class="hero-background-image"`, and the three
 *  photographs on a real client site were classified `decor` and dropped
 *  because of it, so the import attached no pictures to anything. A texture,
 *  meanwhile, is nearly always painted with CSS rather than placed in the DOM,
 *  and every unambiguous decoration word (pattern, texture, gradient, noise…)
 *  still demotes an `<img>` on its own. Found on a real source, 2026-08-16. */
const CSS_DECOR_PREFIXES = ["background", "bakgrund"] as const;

const PORTRAIT_PREFIXES = [
  "team",
  "staff",
  "personal",
  "medarbetar",
  "anstalld",
  "anställd",
  "portrait",
  "portratt",
  "porträtt",
  "headshot",
  "profile",
  "profil",
  "avatar",
  "forfattar",
  "författar",
  "grundare",
  "founder",
] as const;

/**
 * A quality-standard mark: a scheme name next to its number, the way a badge
 * file is almost always named ("iso-9001-2024.png", "en1090.svg", "ce-2024").
 * Split into tokens this reads as `iso` followed by a numeric token.
 */
function namesAStandard(hints: readonly string[]): boolean {
  const SCHEMES = ["iso", "en", "ce", "sis", "ssg", "bf9k"];
  return hints.some((h, i) => {
    if (/^(iso|en|ce|sis|ssg)\d{3,}$/.test(h) || h === "bf9k") return true;
    const next = hints[i + 1];
    return SCHEMES.includes(h) && next !== undefined && /^\d{3,}$/.test(next);
  });
}

/** Below this, in either declared dimension, nothing is content. */
const ICON_MAX_DIM = 80;
/** A picture the page declared this wide is a photograph by construction. */
const PHOTO_MIN_DIM = 400;
/** Wider than tall by this much, and short, reads as a logo lockup or a rule. */
const LOGO_MIN_RATIO = 4;

/** Per-page ceiling on candidates. The old limit was 16, which truncated real
 *  gallery pages; the binding budget is the SITE-wide asset cap in
 *  `htmlToSections.ts`, not this. This only stops a pathological page from
 *  making the vision prompt enormous. */
export const MAX_CANDIDATES_PER_PAGE = 40;

function decode(s: string): string {
  return decodeHtmlEntities(s).trim();
}

/** Attributes of one tag, lowercased keys, entity-decoded values. */
function attrs(tag: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const m of tag.matchAll(
    /([a-zA-Z_:][-a-zA-Z0-9_:.]*)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'>=`]+))/g,
  )) {
    out[m[1].toLowerCase()] = decode(m[2] ?? m[3] ?? m[4] ?? "");
  }
  return out;
}

/**
 * Largest URL in a `srcset`. Handles `w`, `x` and bare descriptors; a malformed
 * list degrades to its first entry rather than losing the image.
 */
export function largestFromSrcset(srcset: string): string | null {
  let best: { url: string; weight: number } | null = null;
  for (const part of srcset.split(",")) {
    const bits = part.trim().split(/\s+/);
    const url = bits[0];
    if (!url) continue;
    const desc = bits[1] ?? "";
    // A `w` descriptor is a pixel width; an `x` descriptor is a density. They
    // never appear in the same list, so comparing them numerically is safe.
    const weight = /^(\d+(?:\.\d+)?)[wx]$/i.test(desc)
      ? parseFloat(desc)
      : 1;
    if (!best || weight > best.weight) best = { url, weight };
  }
  return best?.url ?? null;
}

/** Every `url(...)` inside a style attribute or CSS declaration block. */
function backgroundUrls(css: string): string[] {
  return [...css.matchAll(/url\(\s*['"]?([^'")]+)['"]?\s*\)/gi)].map((m) => m[1]);
}

/**
 * Byte ranges covered by `<tag>…</tag>`, nesting-aware. Used to answer "was this
 * image inside the header?" without a DOM. A tag that is never closed extends to
 * the end of the document, which is what a browser does too.
 */
export function tagRanges(html: string, tag: string): Array<[number, number]> {
  const ranges: Array<[number, number]> = [];
  const stack: number[] = [];
  const re = new RegExp(`<(/?)${tag}\\b[^>]*>`, "gi");
  for (const m of html.matchAll(re)) {
    const at = m.index ?? 0;
    if (m[1]) {
      const start = stack.pop();
      if (start !== undefined) ranges.push([start, at + m[0].length]);
    } else if (!/\/>$/.test(m[0])) {
      stack.push(at);
    }
  }
  // Unclosed tags run to the end.
  for (const start of stack) ranges.push([start, html.length]);
  return ranges;
}

function inAnyRange(ranges: Array<[number, number]>, at: number): boolean {
  return ranges.some(([a, b]) => at >= a && at < b);
}

/** Heading text and offset, so a candidate can name the section it sat under. */
function headingPositions(html: string): Array<{ at: number; text: string }> {
  const out: Array<{ at: number; text: string }> = [];
  for (const m of html.matchAll(/<h([1-4])[^>]*>([\s\S]*?)<\/h\1>/gi)) {
    const text = decode(m[2].replace(/<[^>]+>/g, " ").replace(/\s+/g, " "));
    if (text.length > 1 && text.length < 160) out.push({ at: m.index ?? 0, text });
  }
  return out;
}

/** The filename of a URL, or the whole URL when it will not parse. */
function filenameOf(url: string): string {
  try {
    return new URL(url).pathname.split("/").pop() ?? "";
  } catch {
    return url;
  }
}

/**
 * The deterministic role. Ordered most-certain first: an explicit size below the
 * icon floor beats every text hint, and a text hint beats position.
 *
 * Note what is NOT here: document order. Being first on the page is not evidence
 * of being the subject of the page - that assumption is the whole bug.
 */
export function guessRole(c: Omit<ImageCandidate, "guess">): ImageRole {
  const hints = c.hints;
  const isCert = matches(hints, CERT_PREFIXES) || namesAStandard(hints);
  const { width: w, height: h } = c;

  // An SVG is a drawing. It is a logo or an icon, never photography.
  if (/\.svg(\?|#|$)/i.test(c.url)) {
    return isCert ? "certificate" : matches(hints, LOGO_PREFIXES) ? "logo" : "icon";
  }
  // Declared tiny: furniture, whatever it is called.
  if ((w !== undefined && w <= ICON_MAX_DIM) || (h !== undefined && h <= ICON_MAX_DIM)) {
    return "icon";
  }
  if (matches(hints, ICON_PREFIXES)) return "icon";
  // Certification before logo: a badge is usually ALSO called a logo by the
  // markup around it ("partner-logo iso-cert"), and the badge reading is the
  // one that keeps it out of a hero.
  if (isCert) return "certificate";
  if (matches(hints, LOGO_PREFIXES)) return "logo";
  if (matches(hints, PORTRAIT_PREFIXES)) return "portrait";
  if (matches(hints, DECOR_PREFIXES)) return "decor";
  if (c.source === "background" && matches(hints, CSS_DECOR_PREFIXES)) return "decor";
  // A wide, short raster with no other signal is a lockup or a banner rule.
  if (w !== undefined && h !== undefined && h > 0 && w / h >= LOGO_MIN_RATIO && h < 200) {
    return "logo";
  }
  // Position, only once nothing else spoke. Chrome regions carry brand marks.
  if (c.region === "header" || c.region === "nav" || c.region === "footer") {
    return w !== undefined && w >= PHOTO_MIN_DIM ? "photo" : "logo";
  }
  // A CSS background inside the body is usually a section's cover photo, but it
  // is just as often a texture; `decor` would hide real covers, so it stays a
  // photo and the vision pass (or the size floor) sorts it out.
  return "photo";
}

/**
 * Every picture on one page, in document order, deduped by URL.
 *
 * `baseUrl` resolves relative sources. Data URIs are skipped (they are almost
 * always icons, and they cannot be re-fetched at commit time anyway).
 */
export function imageCandidates(html: string, baseUrl: string): ImageCandidate[] {
  // `at` IS the doc offset; it is renamed on the way out so the public shape
  // reads as a candidate rather than a parser intermediate.
  const found: Array<
    Omit<ImageCandidate, "index" | "guess" | "docOffset"> & { at: number }
  > = [];
  const seen = new Set<string>();
  const headings = headingPositions(html);
  const regions: Array<[ImageCandidate["region"], Array<[number, number]>]> = [
    ["header", tagRanges(html, "header")],
    ["nav", tagRanges(html, "nav")],
    ["footer", tagRanges(html, "footer")],
    ["aside", tagRanges(html, "aside")],
  ];

  const regionAt = (at: number): ImageCandidate["region"] => {
    for (const [name, ranges] of regions) {
      if (inAnyRange(ranges, at)) return name;
    }
    return "body";
  };

  const headingAt = (at: number): string | undefined => {
    let best: string | undefined;
    for (const h of headings) {
      if (h.at < at) best = h.text;
      else break;
    }
    return best;
  };

  const push = (
    raw: string,
    at: number,
    source: ImageCandidate["source"],
    extra: { alt?: string; width?: number; height?: number; hints?: string[] } = {},
  ) => {
    if (!raw || /^data:/i.test(raw)) return;
    let url: string;
    try {
      url = new URL(raw, baseUrl).toString();
    } catch {
      return;
    }
    if (!/^https?:/i.test(url)) return;
    if (seen.has(url)) return;
    seen.add(url);
    const hints = [...(extra.hints ?? []), filenameOf(url)]
      .join(" ")
      .toLowerCase()
      .split(/[\s/_\-.]+/)
      .filter(Boolean);
    found.push({
      url,
      alt: extra.alt ?? "",
      ...(extra.width !== undefined ? { width: extra.width } : {}),
      ...(extra.height !== undefined ? { height: extra.height } : {}),
      region: regionAt(at),
      source,
      ...(headingAt(at) ? { nearestHeading: headingAt(at) } : {}),
      hints,
      at,
    });
  };

  // The page's own representative image, if it declared one. This is the single
  // most reliable hero signal on the page and the old extractor ignored it.
  const og =
    html.match(
      /<meta[^>]+(?:property|name)=["']og:image(?::url)?["'][^>]*content=["']([^"']+)["']/i,
    ) ??
    html.match(
      /<meta[^>]+content=["']([^"']+)["'][^>]*(?:property|name)=["']og:image(?::url)?["']/i,
    );
  if (og?.[1]) push(decode(og[1]), 0, "og", { hints: ["og", "hero"] });

  // <picture>: the <source> list is the real art direction, the nested <img> is
  // the fallback. Take the largest source, and let the <img> pass below dedupe.
  for (const m of html.matchAll(/<picture\b[^>]*>([\s\S]*?)<\/picture>/gi)) {
    const at = m.index ?? 0;
    const inner = m[1];
    const imgTag = inner.match(/<img\b[^>]*>/i)?.[0] ?? "";
    const a = attrs(imgTag);
    let best: string | null = null;
    for (const s of inner.matchAll(/<source\b[^>]*>/gi)) {
      const sa = attrs(s[0]);
      const pick = largestFromSrcset(sa.srcset ?? sa["data-srcset"] ?? "");
      if (pick) best = pick;
    }
    if (best) {
      push(best, at, "picture", {
        alt: a.alt ?? "",
        ...(a.width && /^\d+$/.test(a.width) ? { width: Number(a.width) } : {}),
        ...(a.height && /^\d+$/.test(a.height) ? { height: Number(a.height) } : {}),
        hints: [a.class ?? "", a.id ?? ""],
      });
    }
  }

  for (const m of html.matchAll(/<img\b[^>]*>/gi)) {
    const at = m.index ?? 0;
    const a = attrs(m[0]);
    // Lazy loaders keep the real file in a data attribute and put a 1x1 GIF or a
    // blurred placeholder in `src`. Prefer the real one; the placeholder is
    // dropped as a data URI or caught by the icon floor.
    const lazy =
      a["data-src"] ??
      a["data-lazy-src"] ??
      a["data-original"] ??
      largestFromSrcset(a["data-srcset"] ?? "") ??
      undefined;
    const fromSrcset = largestFromSrcset(a.srcset ?? "");
    const raw = lazy ?? fromSrcset ?? a.src ?? "";
    const width = a.width && /^\d+$/.test(a.width) ? Number(a.width) : undefined;
    const height = a.height && /^\d+$/.test(a.height) ? Number(a.height) : undefined;
    push(raw, at, lazy ? "lazy" : "img", {
      alt: a.alt ?? "",
      ...(width !== undefined ? { width } : {}),
      ...(height !== undefined ? { height } : {}),
      hints: [a.class ?? "", a.id ?? "", a.title ?? ""],
    });
  }

  // Inline `style="background-image:url(…)"`. Section covers on hand-built and
  // Elementor/Divi pages live here and nowhere else, so skipping them lost the
  // biggest picture on the page.
  for (const m of html.matchAll(/<([a-zA-Z][\w-]*)\b([^>]*\bstyle\s*=\s*(?:"[^"]*"|'[^']*'))[^>]*>/g)) {
    const at = m.index ?? 0;
    const a = attrs(m[0]);
    if (!a.style || !/background/i.test(a.style)) continue;
    for (const raw of backgroundUrls(a.style)) {
      push(raw, at, "background", { hints: [a.class ?? "", a.id ?? ""] });
    }
  }

  return found
    .sort((a, b) => a.at - b.at)
    .slice(0, MAX_CANDIDATES_PER_PAGE)
    .map((f, index) => {
      // `at` is a parse-time offset, not part of the candidate contract.
      const base: Omit<ImageCandidate, "guess"> = {
        url: f.url,
        alt: f.alt,
        index,
        docOffset: f.at,
        region: f.region,
        source: f.source,
        hints: f.hints,
        ...(f.width !== undefined ? { width: f.width } : {}),
        ...(f.height !== undefined ? { height: f.height } : {}),
        ...(f.nearestHeading ? { nearestHeading: f.nearestHeading } : {}),
      };
      return { ...base, guess: guessRole(base) };
    });
}

/**
 * Overlay a vision model's verdicts onto the deterministic classification.
 *
 * A URL the model did not answer for keeps its `guess` untouched, so a partial
 * or failed pass degrades to exactly the previous behaviour rather than to a
 * blank page. Alt text is only ever FILLED IN, never replaced: what the author
 * wrote about their own photograph outranks what a model thinks it sees.
 */
export function applyVerdicts(
  candidates: readonly ImageCandidate[],
  verdicts: ReadonlyMap<string, { role: ImageRole; alt?: string }>,
): ImageCandidate[] {
  if (verdicts.size === 0) return [...candidates];
  return candidates.map((c) => {
    const v = verdicts.get(c.url);
    if (!v) return c;
    return {
      ...c,
      guess: v.role,
      ...(c.alt ? {} : v.alt ? { alt: v.alt } : {}),
    };
  });
}

/**
 * The photography pool, best first, with furniture removed.
 *
 * "Best" is deliberately not document order: an `og:image` is the page's own
 * answer to "what is this page a picture of", a body photo beats a chrome one,
 * and a picture the author bothered to write alt text for beats one they did
 * not. Ties keep document order so a gallery stays in the order it was laid out.
 */
export function rankedPhotos(candidates: ImageCandidate[]): ImageCandidate[] {
  const score = (c: ImageCandidate): number => {
    let s = 0;
    if (c.source === "og") s += 100;
    if (c.guess === "hero") s += 80;
    if (c.guess === "portrait") s += 10;
    if (c.region === "body") s += 20;
    if (c.alt.length > 0) s += 10;
    if (c.width !== undefined && c.width >= PHOTO_MIN_DIM) s += 15;
    if (c.source === "background") s -= 5;
    return s;
  };
  return candidates
    .filter((c) => RENDERABLE_ROLES.has(c.guess))
    .map((c, i) => ({ c, i, s: score(c) }))
    .sort((a, b) => b.s - a.s || a.i - b.i)
    .map((x) => x.c);
}
