// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/import/layoutObserve.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

import { decodeHtmlEntities } from "../html/entities";
import { normalizeShape, type LayoutShape, type ShapeRole } from "../sections/layoutShape";

// ---------------------------------------------------------------------------
// Read the STRUCTURE of the blocks on an imported page - never their content.
// The output is a list of `LayoutShape`s: roles, whether something repeats, how
// much imagery is involved, and whether the repeated part scrolls sideways on a
// phone. No text, no image URLs, no colours, no class names, no markup ever
// leaves this module.
//
// Pure + regex-based like the rest of lib/import, so it runs inside a Convex
// action and is fully unit-testable.
// ---------------------------------------------------------------------------

/** Blocks per page we look at. A real page has a handful; the cap keeps a
 *  hostile or generated page from turning one import into thousands of scans. */
const MAX_BLOCKS = 12;
/** A block shorter than this is a divider or a stray wrapper, not a layout. */
const MIN_BLOCK_CHARS = 200;
const MAX_BLOCK_CHARS = 40_000;

const PRICE_RE =
  /(?:kr|SEK|€|\$|£)\s?\d[\d\s.,]*|\d[\d\s.,]*\s?(?:kr|:-|SEK|€|\$|£|\/\s?(?:mån|mo|month|månad|tim|hour|h))/i;

const SCROLL_HINT =
  /overflow-x|scroll-snap|swiper|slick|carousel|slider|marquee|embla|keen-slider|flickity|glide/i;

const DECORATIVE_IMAGE =
  /(icon|logo|sprite|favicon|avatar|badge|pixel|spacer|blank|placeholder)/i;

function stripTags(html: string): string {
  return decodeHtmlEntities(html.replace(/<[^>]+>/g, " ")).replace(/\s+/g, " ").trim();
}

/** Strip the parts that would otherwise be read as page structure. */
function withoutChrome(html: string): string {
  return html
    .replace(/<(script|style|noscript|template|svg)[\s\S]*?<\/\1>/gi, " ")
    .replace(/<(header|nav|footer)[\s\S]*?<\/\1>/gi, " ");
}

/** Content images only - a logo or an icon says nothing about the layout. */
function contentImages(html: string): number {
  let count = 0;
  for (const m of html.matchAll(/<img[^>]*>/gi)) {
    if (DECORATIVE_IMAGE.test(m[0])) continue;
    count++;
  }
  count += [...html.matchAll(/<video[\s>]/gi)].length;
  return count;
}

/** Split a page into its top-level blocks. `<section>`/`<article>` when the
 *  page uses them, otherwise the regions between top-level headings. */
export function splitBlocks(html: string): string[] {
  const page = withoutChrome(html);
  const tagged = scanBalanced(page, ["section", "article"]);
  const blocks = tagged.length >= 2 ? tagged : splitByHeadings(page);
  return blocks
    .map((block) => block.slice(0, MAX_BLOCK_CHARS))
    .filter((block) => block.length >= MIN_BLOCK_CHARS)
    .slice(0, MAX_BLOCKS);
}

/** Depth-aware scan for the OUTERMOST occurrences of the given tags, so a
 *  `<section>` nested inside another is read as part of its parent block. */
function scanBalanced(html: string, tags: string[]): string[] {
  const out: string[] = [];
  const pattern = new RegExp(`<(/?)(${tags.join("|")})\\b[^>]*>`, "gi");
  let depth = 0;
  let start = -1;
  for (const match of html.matchAll(pattern)) {
    const closing = match[1] === "/";
    const at = match.index ?? 0;
    if (!closing) {
      if (depth === 0) start = at;
      depth++;
    } else if (depth > 0) {
      depth--;
      if (depth === 0 && start >= 0) {
        out.push(html.slice(start, at + match[0].length));
        start = -1;
        if (out.length >= MAX_BLOCKS * 2) break;
      }
    }
  }
  return out;
}

function splitByHeadings(html: string): string[] {
  const out: string[] = [];
  const re = /<h[12][^>]*>[\s\S]*?(?=<h[12][\s>]|$)/gi;
  for (const match of html.matchAll(re)) out.push(match[0]);
  return out;
}

/** The repeated card/row inside a block, if there is one. Two ways a repeat
 *  shows up in real markup: a list, or three-plus siblings sharing a class. */
function findRepeat(
  block: string,
): { count: number; sample: string; start: number; end: number } | null {
  const items = [...block.matchAll(/<li\b[^>]*>([\s\S]*?)<\/li>/gi)];
  if (items.length >= 3) {
    const first = items[0];
    const last = items[items.length - 1];
    return {
      count: items.length,
      sample: first[1],
      start: first.index ?? 0,
      end: (last.index ?? 0) + last[0].length,
    };
  }
  const byClass = new Map<string, { count: number; first: number }>();
  for (const match of block.matchAll(/<(div|article|li|a|section)\b[^>]*class=["']([^"']+)["'][^>]*>/gi)) {
    const first = match[2].trim().split(/\s+/)[0];
    if (!first) continue;
    const key = `${match[1].toLowerCase()}.${first}`;
    const seen = byClass.get(key);
    if (seen) seen.count++;
    else byClass.set(key, { count: 1, first: match.index ?? 0 });
  }
  let best: { key: string; count: number; first: number } | null = null;
  for (const [key, value] of byClass) {
    if (value.count < 3) continue;
    if (!best || value.count > best.count) best = { key, ...value };
  }
  if (!best) return null;
  // One repeated element ≈ the span from its first occurrence to the next one.
  const tag = best.key.split(".")[0];
  const cls = best.key.slice(tag.length + 1);
  const re = new RegExp(`<${tag}\\b[^>]*class=["'][^"']*\\b${escapeRe(cls)}\\b`, "gi");
  const hits = [...block.matchAll(re)].map((m) => m.index ?? 0);
  const sample =
    hits.length >= 2 ? block.slice(hits[0], hits[1]) : block.slice(hits[0], hits[0] + 2000);
  const last = hits[hits.length - 1];
  return {
    count: best.count,
    sample,
    start: hits[0],
    end: Math.min(block.length, last + sample.length),
  };
}

function escapeRe(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Structural roles present in one chunk of markup. */
function rolesIn(chunk: string, opts: { minTextChars: number }): ShapeRole[] {
  const roles: ShapeRole[] = [];
  if (/<h[1-6][\s>]/i.test(chunk)) roles.push("heading");

  const paragraphs = [...chunk.matchAll(/<p\b[^>]*>([\s\S]*?)<\/p>/gi)].map((m) => stripTags(m[1]));
  const prose = paragraphs.some((p) => p.length >= opts.minTextChars);
  if (prose) roles.push("text");

  if (contentImages(chunk) > 0) roles.push("media");

  const hasButton =
    /<button\b/i.test(chunk) ||
    /role=["']button["']/i.test(chunk) ||
    /<a\b[^>]*class=["'][^"']*\b(btn|button|cta)\b/i.test(chunk);
  if (hasButton) roles.push("cta");

  if (/<(form|input|textarea|select)\b/i.test(chunk)) roles.push("form");
  if (PRICE_RE.test(stripTags(chunk))) roles.push("price");
  if (/<(blockquote|q)\b/i.test(chunk)) roles.push("quote");
  if (/<svg\b/i.test(chunk) || /class=["'][^"']*\bicon\b/i.test(chunk)) roles.push("icon");
  if (/<time\b/i.test(chunk)) roles.push("date");
  if (/href=["'][^"']+\.(pdf|docx?|xlsx?|pptx?)(["'?#])/i.test(chunk)) roles.push("file");
  if (/<iframe\b[^>]*(maps\.google|openstreetmap|google\.com\/maps)/i.test(chunk)) roles.push("map");

  return roles;
}

/** Describe ONE block structurally. */
export function observeBlock(block: string): LayoutShape {
  const repeat = findRepeat(block);
  const itemRoles = repeat ? rolesIn(repeat.sample, { minTextChars: 20 }) : null;
  // Section-level roles read from the block MINUS the whole repeated region, so
  // a card's heading doesn't also count as the block's heading.
  const outer = repeat ? `${block.slice(0, repeat.start)} ${block.slice(repeat.end)}` : block;
  const roles = rolesIn(outer, { minTextChars: 40 });
  const images = contentImages(block);
  const media: LayoutShape["media"] =
    itemRoles?.includes("media") || images > 1 ? "many" : images === 1 ? "one" : "none";
  const flow: LayoutShape["flow"] = repeat && SCROLL_HINT.test(block) ? "carousel" : "stack";
  return normalizeShape({ roles, itemRoles, media, flow });
}

/** Every distinct block structure on one page, de-duplicated. */
export function observeLayouts(html: string): LayoutShape[] {
  const seen = new Set<string>();
  const out: LayoutShape[] = [];
  for (const block of splitBlocks(html)) {
    const shape = observeBlock(block);
    const key = JSON.stringify(shape);
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(shape);
  }
  return out;
}
