// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/import/measureSource.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

// ---------------------------------------------------------------------------
// ONE measurement boundary, for every editable import lane.
//
// Reading the design off a RENDERED page (`sampleComputedStyles.ts`) is what
// took an import from "our type scale wearing their words" to the source's own
// type, rhythm and colour. Until this module existed that upgrade was wired to
// exactly one call site — the whole-site crawl's home page
// (`convex/importWholeSiteNode.ts`) — so four of the six ways a site enters the
// product silently got the OLD static-guess result and no explanation:
//
//   whole-site URL crawl  -> measured (home page only)
//   single-page URL       -> measured
//   pasted HTML           -> measured when a live URL came with it
//   folder / codebase zip -> NOT measured   (no address to render; says so)
//   Site Kit bundle       -> measured when the bundle names the page it was
//                            authored from (`site.provenance.sourceUrl`), and
//                            then only UNDER the authored theme: everything
//                            the developer stated wins, the measurement fills
//                            gaps (lib/import/measuredTheme.ts). A bundle
//                            without it is still whatever the developer wrote.
//
// So the last lane with no measurement at all is the one with no address to
// render, which is the only honest reason left.
//
// The fix is to make measurement a step that runs on a SOURCE rather than on a
// URL, and — just as important — to make a source that could not be measured
// say WHY. A silent downgrade is why owners conclude the importer is bad.
//
// This module is pure and browser-free: it owns the decision (can this source be
// measured, and if not, what does the owner need to hear), and delegates the
// actual render to the injected `renderUrl`, which today is the browser-backed
// import provider's `sampleDesign`.
// ---------------------------------------------------------------------------

import type { ComputedSample } from "./designExtract";
import { parseHttpUrl } from "../net/url";

/** What a caller hands the importer. `files` covers every archive lane (folder
 *  upload, platform export, codebase zip): the archive is evidence, never
 *  runtime, so nothing in it is executed — and with no address there is nothing
 *  to render either. */
export type MeasureSource =
  | { kind: "url"; url: string }
  | { kind: "html"; html: string; baseUrl?: string }
  | { kind: "files" };

/** Why a source was not measured. Each maps to one sentence the owner reads,
 *  and each is actionable: two of the three tell them exactly what to do
 *  instead (supply the address / configure a rendering provider). */
export type MeasureSkipReason =
  /** No rendering provider is configured, so nothing can be rendered at all. */
  | "no-renderer"
  /** A renderer ran and produced nothing usable (blocked, timed out, or served
   *  an unstyled page — a static guess beats a confidently wrong measurement). */
  | "render-failed"
  /** The source is a document or an archive with no live address to render. */
  | "no-live-url";

export type MeasureResult =
  /** `url` is the ADDRESS that was rendered. Absent for an archive: a folder
   *  has no address, and since 2026-08-03 it does not need one - the owner's
   *  own browser renders it in a sandboxed iframe and sends the numbers back
   *  (lib/import/archiveMeasure.ts). "Measured" and "has an address" stopped
   *  being the same question, so the type says so. */
  | { measured: true; sample: ComputedSample; url?: string }
  | { measured: false; reason: MeasureSkipReason };

export type MeasureDeps = {
  /** Render the URL and read the painted design off it. `null`/absent means no
   *  renderer is configured — the keyless crawler has no browser. Never throws
   *  by contract, but this module defends anyway: a measurement failure must
   *  degrade an import, never fail it. */
  renderUrl?: ((url: string) => Promise<ComputedSample | null>) | null;
};

/** Placeholder base used by the pasted-HTML lane when the owner gave no
 *  address. Not a real host, so never worth a render attempt. */
const PLACEHOLDER_BASE = /^https?:\/\/(imported\.local|blank\.local)\b/i;

/** A base URL is only worth rendering when it addresses the owner's real, live
 *  page. Rendering `https://imported.local/` would measure a DNS failure. */
function liveUrl(raw: string | undefined): string | null {
  if (!raw) return null;
  if (PLACEHOLDER_BASE.test(raw)) return null;
  // The SSRF guard belongs HERE, not in each caller. It used to live only in
  // the two lanes that happened to call `parseHttpUrl` before reaching this
  // module; the Site Kit bundle lane takes its URL out of an uploaded file, and
  // when it was added it had no such caller-side guard, so
  // `http://169.254.169.254/` — dotted, so the hostname test below waves it
  // through — would have been handed to the renderer. The render runs on the
  // rendering vendor's infrastructure, so that is their metadata service being
  // hit from our account: a reflected fetch pointed at a third party of the
  // uploader's choosing, which is exactly what `PORTABLE_CAPS`' own comments
  // set out to prevent. Guarding the boundary means no future lane can forget.
  //
  // `parseHttpUrl` rejects non-http(s), embedded credentials, and every private
  // or reserved IP literal in both address families, including the forms a
  // hostname regex misses (`[::1]`, `[::ffff:169.254.169.254]`, and IPv4 in
  // decimal/hex/octal, which WHATWG `URL` normalises first).
  const parsed = parseHttpUrl(raw);
  if (!parsed) return null;
  // A bare hostname with no dot is a LAN name, not a site someone published.
  if (!parsed.hostname.includes(".")) return null;
  return parsed.toString();
}

/**
 * Measure one import source. Returns the measured sample, or the reason the
 * measurement did not run — never throws, and never fails the import.
 *
 * The pasted-HTML lane measures the live page when the owner supplied its
 * address. That is deliberate rather than a shortcut: it is what makes "import
 * this URL" and "paste this page's HTML" produce the SAME theme instead of two
 * different-looking sites from one source.
 */
export async function measureSource(
  source: MeasureSource,
  deps: MeasureDeps = {},
): Promise<MeasureResult> {
  const target =
    source.kind === "url"
      ? liveUrl(source.url)
      : source.kind === "html"
        ? liveUrl(source.baseUrl)
        : null;
  if (!target) return { measured: false, reason: "no-live-url" };
  if (!deps.renderUrl) return { measured: false, reason: "no-renderer" };

  let sample: ComputedSample | null = null;
  try {
    sample = await deps.renderUrl(target);
  } catch (error) {
    console.warn("[import] design measurement failed; using static extraction", error);
    return { measured: false, reason: "render-failed" };
  }
  // An empty sample carries no information: the renderer produced an unstyled
  // page, or every value it read was junk the normaliser dropped. Either way the
  // static guess is the better answer, and the owner should hear that we tried.
  if (!sample || Object.keys(sample).length === 0) {
    return { measured: false, reason: "render-failed" };
  }
  return { measured: true, sample, url: target };
}

// --- More than the home page (backlog 1725 item 4) --------------------------

/** The three page shapes a small-business site is actually built from. Naming
 *  them is the point: per-section geometry measured on the home page is a
 *  measurement THERE and a guess anywhere else, so a subpage either gets its
 *  own render or gets nothing. */
export type PageTemplate = "home" | "content" | "post";

/** A blog/news post's URL. Two segments under a news-ish parent is the shape
 *  every builder emits; a one-segment `/om-oss` is a content page. */
const POST_PATH =
  /\/(?:blogg?|nyheter|artiklar|inlagg|insights?|news|posts?|articles?|journal)\/[^/]+\/?$/i;

/**
 * Which pages of a crawl are worth their own render.
 *
 * A render costs money on a metered provider and wall-clock on every import,
 * so this returns at most one page per template and never more than `max`.
 * That is the whole trade: measuring three pages makes per-section geometry
 * differ between a landing page and an article — which is the reason item 1's
 * per-band overrides exist — without turning a 30-page crawl into 30 renders.
 *
 * The home page is always first and always included; it is the one whose
 * measurement also sets the site's theme.
 */
export function pickTemplatePages(
  urls: ReadonlyArray<string>,
  homeUrl: string,
  max = 3,
): Array<{ url: string; template: PageTemplate }> {
  const out: Array<{ url: string; template: PageTemplate }> = [];
  const home = urls.find((u) => u === homeUrl) ?? urls[0];
  if (home === undefined) return out;
  out.push({ url: home, template: "home" });
  const pathOf = (raw: string): string => {
    try {
      return new URL(raw).pathname;
    } catch {
      return raw;
    }
  };
  const rest = urls.filter((u) => u !== home);
  const post = rest.find((u) => POST_PATH.test(pathOf(u)));
  // A content page is any other subpage. Deliberately the FIRST one in crawl
  // order rather than a keyword pick ("om-oss", "tjanster"): the crawl already
  // ordered pages by how central they are, and a keyword list would just be a
  // guess about which subpage is representative.
  const content = rest.find((u) => u !== post && pathOf(u) !== "/" && pathOf(u) !== "");
  if (content) out.push({ url: content, template: "content" });
  if (post) out.push({ url: post, template: "post" });
  return out.slice(0, Math.max(1, max));
}

/** The report field the import screens already render (`"rendered"` = measured
 *  off a real render, `"static"` = parsed from source CSS). Kept as a helper so
 *  every lane derives it the same way instead of re-deciding per call site. */
export function designSourceOf(result: MeasureResult): "rendered" | "static" {
  return result.measured ? "rendered" : "static";
}
