// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/brand.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

/** Product brand name shown to users. Owner decision Q6/Q9 (2026-07-04):
 *  "SnabbSajt" everywhere, swappable from this single constant. The domain
 *  (snabbsajt.com) and internal code/table names are unaffected. */
export const BRAND_NAME = "SnabbSajt";
