// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/socials.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

// Social / business profile platforms. Shared by the settings UI, the footer
// social bar, the content scraper, and SEO sameAs. Pure (no imports) so it's
// safe to use from Convex functions and the client.

export const SOCIAL_PLATFORMS = [
  "linkedin",
  "facebook",
  "instagram",
  "google",
  "x",
  "youtube",
  "tiktok",
] as const;

export type SocialPlatform = (typeof SOCIAL_PLATFORMS)[number];

export const SOCIAL_META: Record<
  SocialPlatform,
  { label: string; placeholder: string; hosts: string[] }
> = {
  linkedin: { label: "LinkedIn", placeholder: "https://linkedin.com/company/…", hosts: ["linkedin.com"] },
  facebook: { label: "Facebook", placeholder: "https://facebook.com/…", hosts: ["facebook.com", "fb.com", "fb.me"] },
  instagram: { label: "Instagram", placeholder: "https://instagram.com/…", hosts: ["instagram.com"] },
  google: {
    label: "Google Business",
    placeholder: "https://g.page/…",
    hosts: ["business.google.com", "g.page", "maps.app.goo.gl", "goo.gl/maps", "maps.google."],
  },
  x: { label: "X (Twitter)", placeholder: "https://x.com/…", hosts: ["x.com", "twitter.com"] },
  youtube: { label: "YouTube", placeholder: "https://youtube.com/@…", hosts: ["youtube.com", "youtu.be"] },
  tiktok: { label: "TikTok", placeholder: "https://tiktok.com/@…", hosts: ["tiktok.com"] },
};

export type SocialsMap = Partial<Record<SocialPlatform, string | undefined>>;

/** Canonical labels for populated social profiles, in the shared display order. */
export function socialPlatformLabels(socials?: SocialsMap): string[] {
  if (!socials) return [];
  return SOCIAL_PLATFORMS.filter((platform) => {
    const url = socials[platform];
    return typeof url === "string" && url.trim().length > 0;
  }).map((platform) => SOCIAL_META[platform].label);
}

/** Non-empty, http(s) social urls in a stable order (for sameAs / footer). */
export function socialUrls(socials?: SocialsMap): string[] {
  if (!socials) return [];
  return SOCIAL_PLATFORMS.map((p) => socials[p]).filter(
    (u): u is string => !!u && /^https?:\/\//i.test(u),
  );
}

/** Which platform a url belongs to, by host match (used by the scraper). */
export function platformForUrl(url: string): SocialPlatform | null {
  let host: string;
  try {
    host = new URL(url).host.toLowerCase();
  } catch {
    return null;
  }
  for (const p of SOCIAL_PLATFORMS) {
    if (SOCIAL_META[p].hosts.some((h) => host.includes(h) || url.includes(h))) {
      return p;
    }
  }
  return null;
}
