// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/tracking.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

// Third-party tracking providers. Pure (no convex/react imports) so it's shared
// by the settings UI, onboarding, the consent gate, the scraper, the privacy
// policy generator, and Convex. The Convex validator that mirrors this lives in
// convex/model/tracking.ts and MUST keep the same keys.
//
// Safety: we only ever store a *validated id* (matched against a strict pattern)
// and later interpolate it into a known, provider-specific snippet. Arbitrary
// user-supplied script is never accepted - this preserves the "no raw HTML"
// model of the rest of the builder.

export const TRACKING_PROVIDERS = [
  "ga4",
  "gtm",
  "metaPixel",
  "linkedin",
  "hubspot",
  "hotjar",
] as const;

export type TrackingProvider = (typeof TRACKING_PROVIDERS)[number];

/** A site's tracking configuration: a validated id per enabled provider. */
export type TrackingConfig = Partial<Record<TrackingProvider, string | undefined>>;

/** Consent buckets. "necessary" needs no consent and is never gated. */
export type ConsentCategory = "analytics" | "marketing";

type Localized = { sv: string; en: string; pl: string };

export type TrackingMeta = {
  label: string;
  /** Which consent bucket(s) this tool falls under. GTM spans both because a
   *  container can load either kind of tag. */
  categories: ConsentCategory[];
  /** Strict id format for manual entry (anchored). */
  pattern: RegExp;
  /** Normalize a matched id to its canonical stored form. */
  normalize: (id: string) => string;
  placeholder: string;
  /** Where to find this id (linked from the picker). */
  helpUrl: string;
  /** Cookies / storage keys this tool sets - disclosed in the privacy policy. */
  cookieNames: string[];
  /** Plain-language outcome shown in the goal picker. */
  outcome: Localized;
  /** What it does - used by the privacy policy generator. */
  purpose: Localized;
};

const upper = (id: string) => id.toUpperCase();
const identity = (id: string) => id;

export const TRACKING_META: Record<TrackingProvider, TrackingMeta> = {
  ga4: {
    label: "Google Analytics",
    categories: ["analytics"],
    pattern: /^G-[A-Z0-9]{4,}$/i,
    normalize: upper,
    placeholder: "G-XXXXXXXXXX",
    helpUrl: "https://support.google.com/analytics/answer/9539598",
    cookieNames: ["_ga", "_ga_*", "_gid"],
    outcome: {
      sv: "Se hur många som besöker sidan och vad de tittar på",
      en: "See how many people visit and what they look at",
      pl: "Zobacz, ile osób odwiedza stronę i co oglądają",
    },
    purpose: {
      sv: "Webbanalys – mäter besök, sidvisningar och beteende.",
      en: "Web analytics – measures visits, page views and behaviour.",
      pl: "Analiza strony – mierzy odwiedziny, wyświetlenia stron i zachowanie.",
    },
  },
  gtm: {
    label: "Google Tag Manager",
    categories: ["analytics", "marketing"],
    pattern: /^GTM-[A-Z0-9]{4,}$/i,
    normalize: upper,
    placeholder: "GTM-XXXXXXX",
    helpUrl: "https://support.google.com/tagmanager/answer/6103696",
    cookieNames: [],
    outcome: {
      sv: "Jag hanterar mina egna taggar (avancerat)",
      en: "I manage my own tags (advanced)",
      pl: "Sam zarządzam swoimi tagami (zaawansowane)",
    },
    purpose: {
      sv: "Tagghanterare – laddar andra mät- och annonsverktyg du själv lägger till.",
      en: "Tag manager – loads other measurement/ad tools you add yourself.",
      pl: "Menedżer tagów – ładuje inne narzędzia pomiarowe i reklamowe, które sam dodasz.",
    },
  },
  metaPixel: {
    label: "Meta Pixel",
    categories: ["marketing"],
    pattern: /^\d{6,20}$/,
    normalize: identity,
    placeholder: "123456789012345",
    helpUrl: "https://www.facebook.com/business/help/952192354843755",
    cookieNames: ["_fbp", "_fbc"],
    outcome: {
      sv: "Mät mina Facebook- och Instagram-annonser",
      en: "Measure my Facebook & Instagram ads",
      pl: "Mierz moje reklamy na Facebooku i Instagramie",
    },
    purpose: {
      sv: "Annonsmätning för Facebook och Instagram (Meta).",
      en: "Ad measurement for Facebook and Instagram (Meta).",
      pl: "Pomiar reklam na Facebooku i Instagramie (Meta).",
    },
  },
  linkedin: {
    label: "LinkedIn Insight Tag",
    categories: ["marketing"],
    pattern: /^\d{3,12}$/,
    normalize: identity,
    placeholder: "1234567",
    helpUrl: "https://www.linkedin.com/help/lms/answer/a418880",
    cookieNames: ["li_sugr", "bcookie", "lidc", "UserMatchHistory", "AnalyticsSyncHistory"],
    outcome: {
      sv: "Mät mina LinkedIn-annonser",
      en: "Measure my LinkedIn ads",
      pl: "Mierz moje reklamy na LinkedInie",
    },
    purpose: {
      sv: "Annonsmätning och målgrupper för LinkedIn.",
      en: "Ad measurement and audiences for LinkedIn.",
      pl: "Pomiar reklam i grupy odbiorców na LinkedInie.",
    },
  },
  hubspot: {
    label: "HubSpot",
    categories: ["marketing"],
    pattern: /^\d{3,12}$/,
    normalize: identity,
    placeholder: "1234567",
    helpUrl: "https://knowledge.hubspot.com/account-management/how-do-i-find-my-hub-id",
    cookieNames: ["__hstc", "__hssrc", "__hssc", "hubspotutk"],
    outcome: {
      sv: "Jag använder HubSpot för leads och chatt",
      en: "I use HubSpot for leads & chat",
      pl: "Używam HubSpot do zapytań i czatu",
    },
    purpose: {
      sv: "Marknadsföring, leads, formulär och chatt via HubSpot.",
      en: "Marketing, leads, forms and chat via HubSpot.",
      pl: "Marketing, zapytania, formularze i czat przez HubSpot.",
    },
  },
  hotjar: {
    label: "Hotjar",
    categories: ["analytics"],
    pattern: /^\d{3,12}$/,
    normalize: identity,
    placeholder: "1234567",
    helpUrl: "https://help.hotjar.com/hc/en-us/articles/115011789248",
    cookieNames: ["_hjSession_*", "_hjid", "_hjIncludedInSessionSample"],
    outcome: {
      sv: "Se var besökare klickar och scrollar (värmekartor)",
      en: "See where visitors click and scroll (heatmaps)",
      pl: "Zobacz, gdzie odwiedzający klikają i przewijają (mapy ciepła)",
    },
    purpose: {
      sv: "Beteendeanalys, värmekartor och inspelningar via Hotjar.",
      en: "Behaviour analytics, heatmaps and recordings via Hotjar.",
      pl: "Analiza zachowań, mapy ciepła i nagrania przez Hotjar.",
    },
  },
};

// Unanchored signatures for sniffing an id out of an existing site's HTML (or a
// pasted snippet). Group 1 is the id when present, otherwise the whole match.
const DETECT: Record<TrackingProvider, RegExp[]> = {
  gtm: [/GTM-[A-Z0-9]{4,}/i],
  ga4: [/\bG-[A-Z0-9]{4,}\b/i],
  metaPixel: [
    /fbq\(\s*['"]init['"]\s*,\s*['"](\d{6,20})['"]/i,
    /facebook\.com\/tr\?id=(\d{6,20})/i,
  ],
  linkedin: [
    /_linkedin_partner_id\s*=\s*["']?(\d{3,12})/i,
    /linkedin_data_partner_ids\.push\(\s*["']?(\d{3,12})/i,
  ],
  hubspot: [
    /js\.hs-scripts\.com\/(\d{3,12})/i,
    /js\.hs-analytics\.net\/analytics\/[^/]+\/(\d{3,12})/i,
  ],
  hotjar: [
    /hjid\s*:\s*(\d{3,12})/i,
    /static\.hotjar\.com\/c\/hotjar-(\d{3,12})/i,
  ],
};

/** Detect configured tracking tools by scanning raw HTML (or a pasted snippet).
 *  Used by the "import from existing site" flow. Best-effort. */
export function detectTrackingFromHtml(html: string): TrackingConfig {
  const found: TrackingConfig = {};
  if (typeof html !== "string" || !html) return found;
  for (const provider of TRACKING_PROVIDERS) {
    for (const re of DETECT[provider]) {
      const m = html.match(re);
      if (m) {
        const id = (m[1] ?? m[0]).trim();
        found[provider] = TRACKING_META[provider].normalize(id);
        break;
      }
    }
  }
  return found;
}

/** Validate + normalize a single id. Returns the canonical id or null.
 *  Forgiving: if the value isn't a bare id we try to sniff one out of it (so a
 *  user can paste a whole snippet). The output is always a constrained id. */
export function validateTrackingId(
  provider: TrackingProvider,
  raw: unknown,
): string | null {
  if (typeof raw !== "string") return null;
  const trimmed = raw.trim();
  if (!trimmed) return null;
  const meta = TRACKING_META[provider];
  if (meta.pattern.test(trimmed)) return meta.normalize(trimmed);
  const sniffed = detectTrackingFromHtml(trimmed)[provider];
  return sniffed ?? null;
}

/** Validate a whole config, dropping any invalid/empty entries. */
export function sanitizeTracking(input: TrackingConfig | undefined): TrackingConfig {
  const out: TrackingConfig = {};
  if (!input) return out;
  for (const provider of TRACKING_PROVIDERS) {
    const id = validateTrackingId(provider, input[provider]);
    if (id) out[provider] = id;
  }
  return out;
}

/** Providers configured, in stable display order. */
export function enabledProviders(tracking: TrackingConfig | undefined): TrackingProvider[] {
  if (!tracking) return [];
  return TRACKING_PROVIDERS.filter((p) => !!tracking[p]);
}

export function hasAnyTracking(tracking: TrackingConfig | undefined): boolean {
  return enabledProviders(tracking).length > 0;
}

/** Which consent categories are actually in play given the configured tools. */
export function usedCategories(
  tracking: TrackingConfig | undefined,
): Record<ConsentCategory, boolean> {
  const used: Record<ConsentCategory, boolean> = { analytics: false, marketing: false };
  for (const p of enabledProviders(tracking)) {
    for (const c of TRACKING_META[p].categories) used[c] = true;
  }
  return used;
}
