// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/booking/embed.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

// Booking-provider detection + embed-URL building. Pure (no imports) so it is
// safe to use from the renderer (server), the editor panel (client) and tests.
//
// The owner stores only a plain booking URL. We DERIVE the provider from that
// URL at render time (never stored → it can't drift from the link) and build an
// iframe src for providers that allow framing; everything else falls back to a
// "Book now" button that opens the link in a new tab. A raw iframe/script is
// never stored - the same constrained model the `video` section uses.

export type BookingProvider =
  | "calendly"
  | "calcom"
  | "microsoft"
  | "google"
  | "acuity"
  | "setmore"
  | "simplybook"
  | "bokadirekt"
  | "goactive"
  | "zoezi"
  | "other";

type ProviderMeta = {
  label: string;
  hosts: string[];
  /** Whether this provider's pages can be embedded inline (iframe). */
  inline: boolean;
};

// Order matters only for display. Detection matches a host or any subdomain of
// it (see `detectBookingProvider`), which is what makes the per-club providers
// below work — a Go Active gym is always `<club>.goactivebooking.com`.
export const BOOKING_PROVIDERS: Record<BookingProvider, ProviderMeta> = {
  calendly: { label: "Calendly", hosts: ["calendly.com"], inline: true },
  calcom: { label: "Cal.com", hosts: ["cal.com"], inline: true },
  microsoft: {
    label: "Microsoft Bookings",
    hosts: [
      "outlook.office365.com",
      "outlook.office.com",
      "bookings.office.com",
      "book.ms",
    ],
    inline: true,
  },
  google: {
    label: "Google",
    hosts: ["calendar.google.com", "calendar.app.google"],
    inline: true,
  },
  acuity: {
    label: "Acuity Scheduling",
    hosts: ["acuityscheduling.com"],
    inline: true,
  },
  setmore: {
    label: "Setmore",
    hosts: ["setmore.com", "booking.setmore.com"],
    inline: true,
  },
  simplybook: {
    label: "SimplyBook.me",
    hosts: ["simplybook.me", "simplybook.it", "simplybook.asia"],
    inline: true,
  },
  // Popular in Sweden but link-only (no official iframe embed) → button.
  bokadirekt: { label: "Bokadirekt", hosts: ["bokadirekt.se"], inline: false },
  // Swedish gym member systems. Every club gets its own subdomain, which the
  // suffix match below handles. `goactivebooking.com` is the member-facing
  // portal and `brpsystems.com` the API host behind it — same vendor, and an
  // owner may paste either. Zoezi clubs live on `gymsystem.se`; `zoezi.se` is
  // only their marketing site and must never be listed (no gym's link is there).
  // Both are link-only: nothing has been verified as safe to iframe.
  goactive: {
    label: "Go Active",
    hosts: ["goactivebooking.com", "brpsystems.com"],
    inline: false,
  },
  zoezi: { label: "Zoezi", hosts: ["gymsystem.se"], inline: false },
  other: { label: "Booking", hosts: [], inline: false },
};

/** Parse a hostname, tolerating a missing scheme (so detection works while the
 *  owner is still typing). Returns null for unparseable input. */
function hostname(url: string): string | null {
  let s = url.trim();
  if (!s) return null;
  if (!/^[a-z][a-z0-9+.-]*:\/\//i.test(s)) s = `https://${s}`;
  try {
    return new URL(s).hostname.toLowerCase().replace(/^www\./, "");
  } catch {
    return null;
  }
}

export function detectBookingProvider(url: string): BookingProvider {
  const host = hostname(url);
  if (!host) return "other";
  for (const key of Object.keys(BOOKING_PROVIDERS) as BookingProvider[]) {
    if (key === "other") continue;
    const { hosts } = BOOKING_PROVIDERS[key];
    if (hosts.some((h) => host === h || host.endsWith(`.${h}`))) return key;
  }
  return "other";
}

/** Only https links are ever embedded or linked - avoids mixed-content on the
 *  (https) published site and rejects junk like "javascript:". */
export function isHttpsUrl(url: string): boolean {
  return /^https:\/\//i.test(url.trim());
}

/** True when a valid https booking URL can be shown inline (iframe). */
export function canEmbedInline(url: string): boolean {
  return isHttpsUrl(url) && BOOKING_PROVIDERS[detectBookingProvider(url)].inline;
}

/** Build an iframe src for an embeddable provider, or null to use the button
 *  fallback. Only ever returns a URL on a recognised provider host. */
export function bookingEmbedSrc(url: string): string | null {
  const clean = url.trim();
  if (!isHttpsUrl(clean)) return null;
  const provider = detectBookingProvider(clean);
  if (!BOOKING_PROVIDERS[provider].inline) return null;
  try {
    const u = new URL(clean);
    // Google appointment schedules only render embedded with gv=true.
    if (provider === "google" && !u.searchParams.has("gv")) {
      u.searchParams.set("gv", "true");
    }
    return u.toString();
  } catch {
    return null;
  }
}

export function bookingProviderLabel(url: string): string {
  return BOOKING_PROVIDERS[detectBookingProvider(url)].label;
}

/** Extract a booking URL from a pasted iframe or provider widget snippet. Raw
 * markup is never stored; callers persist only the extracted https URL. */
export function extractBookingUrl(raw: string): string | null {
  const snippet = raw.trim();
  if (!snippet || !snippet.includes("<")) return null;
  const collect = (pattern: RegExp, group: number): string[] => {
    const matches: string[] = [];
    for (const match of snippet.matchAll(pattern)) matches.push(match[group]);
    return matches;
  };
  const candidates = [
    ...collect(/data-url\s*=\s*["']([^"']+)["']/gi, 1),
    ...collect(/src\s*=\s*["']([^"']+)["']/gi, 1),
    ...collect(/https?:\/\/[^\s"'<>]+/gi, 0),
  ]
    .map((url) => url.trim())
    .filter((url) => isHttpsUrl(url) && !/\.js(\?|#|$)/i.test(url));
  if (candidates.length === 0) return null;
  return candidates.find((url) => detectBookingProvider(url) !== "other") ?? candidates[0];
}
