// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/sections/layoutShape.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

import { sectionContent, type SectionType } from "../../../convex/model/sections";
import { SECTION_REGISTRY } from "../../../lib/sections/registry";

// ---------------------------------------------------------------------------
// Layout shape - the STRUCTURAL idea of a section, with every trace of whose
// site it came from removed. A shape says "a heading, a repeating card with a
// picture and a price, and it scrolls sideways on a phone". It can never say
// which business, which words, which photo, or which colours.
//
// Used for two things:
//   1. deciding whether a layout we saw during an import is something the
//      section registry already offers (then we never ask the owner anything),
//   2. describing an owner-approved layout idea to an internal reviewer.
//
// The registry's own content model is the source of truth: shapes for existing
// blocks are DERIVED from the `sectionContent` validator, so a new section type
// automatically joins the comparison instead of drifting out of a hand-written
// list. Layout variants (image left/right, 2 vs 3 columns, colours, spacing,
// corner radius) are deliberately NOT part of a shape - by definition they do
// not make a layout new.
// ---------------------------------------------------------------------------

/** The structural roles a layout can use. Deliberately small: anything finer
 *  would start describing the customer's content instead of their layout. */
export const SHAPE_ROLES = [
  "heading",
  "text",
  "media",
  "cta",
  "form",
  "price",
  "quote",
  "icon",
  "date",
  "file",
  "rating",
  "map",
] as const;

export type ShapeRole = (typeof SHAPE_ROLES)[number];

/** How the repeated parts behave on a small screen. Only two options, because
 *  only two are structurally different: they stack, or they scroll sideways. */
export type ShapeFlow = "stack" | "carousel";

export type LayoutShape = {
  /** Roles used once, at the top of the block. Sorted + de-duplicated. */
  roles: ShapeRole[];
  /** Roles inside each repeated card/row. `null` when nothing repeats. */
  itemRoles: ShapeRole[] | null;
  /** How much imagery the layout leans on. */
  media: "none" | "one" | "many";
  flow: ShapeFlow;
};

const ROLE_ORDER = new Map(SHAPE_ROLES.map((role, i) => [role, i]));

function sortRoles(roles: Iterable<ShapeRole>): ShapeRole[] {
  return [...new Set(roles)].sort(
    (a, b) => (ROLE_ORDER.get(a) ?? 99) - (ROLE_ORDER.get(b) ?? 99),
  );
}

/** A stable, comparable string for one shape. Two customers who built the same
 *  layout produce the same fingerprint, which is how the review queue collapses
 *  them into a single idea instead of a pile of duplicates. */
export function shapeFingerprint(shape: LayoutShape): string {
  const canonical = normalizeShape(shape);
  const items = canonical.itemRoles ? canonical.itemRoles.join("+") : "-";
  return `r:${canonical.roles.join("+")}|i:${items}|m:${canonical.media}|f:${canonical.flow}`;
}

export function normalizeShape(shape: LayoutShape): LayoutShape {
  const itemRoles = shape.itemRoles ? sortRoles(shape.itemRoles) : null;
  return {
    roles: sortRoles(shape.roles),
    itemRoles: itemRoles && itemRoles.length > 0 ? itemRoles : null,
    media: shape.media,
    flow: shape.flow,
  };
}

// --- deriving shapes from the section content model -------------------------

/** The parts of a Convex validator this module reads. Structural on purpose:
 *  it walks the same object the database validates writes against. */
type ValidatorNode = {
  kind: string;
  fields?: Record<string, ValidatorNode>;
  element?: ValidatorNode;
  members?: ValidatorNode[];
  value?: unknown;
};

/** Exact field-name -> role. Names not listed fall through to the suffix rules
 *  in `roleForField`. */
const FIELD_ROLES: Record<string, ShapeRole> = {
  heading: "heading",
  headline: "heading",
  title: "heading",
  name: "heading",
  question: "heading",
  eyebrow: "heading",
  tagline: "heading",
  label: "heading",
  valueLabel: "heading",
  step: "heading",

  subheadline: "text",
  body: "text",
  intro: "text",
  description: "text",
  text: "text",
  answer: "text",
  bio: "text",
  role: "text",
  caption: "text",
  note: "text",
  subtext: "text",
  footnote: "text",
  legalText: "text",
  contactLine: "text",
  help: "text",
  attribution: "text",
  author: "text",
  period: "text",
  category: "text",
  businessName: "text",
  successMessage: "text",
  insufficientMessage: "text",
  estimateNote: "text",
  features: "text",
  bullets: "text",
  blocks: "text",

  media: "media",
  image: "media",
  images: "media",
  photo: "media",
  avatar: "media",
  logo: "media",
  poster: "media",
  video: "media",
  bgVideo: "media",
  imageUrl: "media",
  videoId: "media",
  videoUrl: "media",
  // videoAutoplay / videoMuted / videoControls are deliberately unmapped:
  // playback settings are not part of a layout's structure.

  cta: "cta",
  links: "cta",

  fields: "form",
  submitLabel: "form",
  consentText: "form",
  placeholder: "form",
  defaultValue: "form",
  options: "form",
  required: "form",
  input: "form",

  price: "price",
  priceText: "price",
  priceMinor: "price",
  currency: "price",
  basePriceMin: "price",
  basePriceMax: "price",
  perUnitMin: "price",
  perUnitMax: "price",
  ratePct: "price",
  pricing: "price",

  icon: "icon",
  rating: "rating",
  document: "file",

  day: "date",
  days: "date",
  open: "date",
  close: "date",
  closed: "date",
  breaks: "date",
  verifiedAt: "date",

  address: "map",
  showMap: "map",
  zoom: "map",
};

function roleForField(field: string): ShapeRole | null {
  const exact = FIELD_ROLES[field];
  if (exact) return exact;
  const lower = field.toLowerCase();
  if (lower.endsWith("cta")) return "cta";
  if (lower.includes("price")) return "price";
  if (/(media|image|photo|video|logo)/.test(lower)) return "media";
  if (/(heading|title)/.test(lower)) return "heading";
  if (/(text|description|body)/.test(lower)) return "text";
  return null;
}

/** Array names that describe what the repeated thing IS, not what it holds. */
const ARRAY_ROLES: Record<string, ShapeRole> = {
  quotes: "quote",
  images: "media",
  logos: "media",
  documents: "file",
  days: "date",
  fields: "form",
};

/** Recognise the shared content refs (`assetRef`, `ctaRef`, `formField`) by the
 *  fields that only they carry, so a repeated asset reads as one "media" role
 *  instead of leaking its focal-point plumbing into the shape. */
function roleForRefObject(fields: Record<string, ValidatorNode>): ShapeRole | null {
  if ("assetId" in fields) return "media";
  if ("target" in fields && "label" in fields) return "cta";
  if ("required" in fields && "key" in fields) return "form";
  return null;
}

function rolesOfObject(fields: Record<string, ValidatorNode>): ShapeRole[] {
  const out: ShapeRole[] = [];
  for (const [name, node] of Object.entries(fields)) {
    if (name === "type") continue;
    if (node.kind === "object" && node.fields) {
      const ref = roleForRefObject(node.fields);
      if (ref) {
        out.push(ref);
        continue;
      }
    }
    const role = roleForField(name);
    if (role) out.push(role);
  }
  return out;
}

/** The repeated part of a section: its first array field, described as roles. */
function itemRolesOf(fields: Record<string, ValidatorNode>): ShapeRole[] | null {
  for (const [name, node] of Object.entries(fields)) {
    if (node.kind !== "array" || !node.element) continue;
    const named = ARRAY_ROLES[name];
    const element = node.element;
    if (element.kind === "object" && element.fields) {
      const ref = roleForRefObject(element.fields);
      if (ref) return sortRoles([ref, ...(named ? [named] : [])]);
      const roles = rolesOfObject(element.fields);
      return sortRoles([...roles, ...(named ? [named] : [])]);
    }
    // An array of plain strings (bullets, features) is a repeated line of text.
    return sortRoles([named ?? roleForField(name) ?? "text"]);
  }
  return null;
}

function unionMembers(): ValidatorNode[] {
  return (sectionContent as unknown as ValidatorNode).members ?? [];
}

export type RegistryShape = {
  type: SectionType;
  shape: LayoutShape;
  fingerprint: string;
};

/** Every layout the product already offers, as shapes. A section type whose
 *  registry entry has a sideways-scrolling variant contributes two shapes (it
 *  genuinely covers both behaviours). */
export function registryShapes(): RegistryShape[] {
  const out: RegistryShape[] = [];
  for (const member of unionMembers()) {
    const fields = member.fields;
    const type = fields?.type?.value;
    if (!fields || typeof type !== "string") continue;
    const sectionType = type as SectionType;
    const itemRoles = itemRolesOf(fields);
    const roles = sortRoles(rolesOfObject(fields));
    const mediaAtTop = roles.filter((r) => r === "media").length;
    const media: LayoutShape["media"] =
      itemRoles?.includes("media") ? "many" : mediaAtTop > 0 ? "one" : "none";
    const flows: ShapeFlow[] = hasScrollingVariant(sectionType)
      ? ["stack", "carousel"]
      : ["stack"];
    for (const flow of flows) {
      const shape = normalizeShape({ roles, itemRoles, media, flow });
      out.push({ type: sectionType, shape, fingerprint: shapeFingerprint(shape) });
    }
  }
  return out;
}

const SCROLLING_VARIANTS = new Set(["carousel", "marquee", "scroll-tabs", "tabs"]);

function hasScrollingVariant(type: SectionType): boolean {
  const def = SECTION_REGISTRY[type];
  if (!def) return false;
  return def.variants.some((variant) => SCROLLING_VARIANTS.has(variant.key));
}

// --- comparing an observed layout with what we already offer ----------------

/** How much of what the observed layout NEEDS an existing block already offers.
 *  Deliberately one-directional: an existing block with extra optional parts
 *  still covers the need, while a missing part is a real gap. */
function coverage(needed: readonly string[], offered: readonly string[]): number {
  if (needed.length === 0) return 1;
  const has = new Set(offered);
  let shared = 0;
  for (const value of new Set(needed)) if (has.has(value)) shared++;
  return shared / new Set(needed).size;
}

/** 0 = nothing in common, 1 = the existing block already covers the idea. */
export function shapeSimilarity(observed: LayoutShape, existing: LayoutShape): number {
  const roleScore = coverage(observed.roles, existing.roles);
  const itemScore =
    observed.itemRoles === null
      ? existing.itemRoles === null
        ? 1
        : 0.5 // we'd offer a repeat they don't need - close, not identical
      : existing.itemRoles === null
        ? 0
        : coverage(observed.itemRoles, existing.itemRoles);
  const mediaScore =
    observed.media === existing.media
      ? 1
      : observed.media !== "none" && existing.media !== "none"
        ? 0.5
        : 0;
  const flowScore = observed.flow === existing.flow ? 1 : 0;
  // The repeated part carries the most weight, and squaring it means a card
  // that needs two parts we don't have (a form and a time, say) reads as a
  // different content model rather than "close enough".
  return 0.3 * roleScore + 0.5 * itemScore * itemScore + 0.1 * mediaScore + 0.1 * flowScore;
}

/** At or above this, the registry already solves the same need. */
export const COVERED_THRESHOLD = 0.8;
/** Between this and COVERED_THRESHOLD, an existing layout is close enough that
 *  a small generic extension is the honest answer, not a whole new block. */
export const EXTENDABLE_THRESHOLD = 0.6;

export const SHAPE_REASONS = [
  "new-repeat",
  "new-item-roles",
  "new-combination",
  "new-flow",
  "new-media-weight",
] as const;

export type ShapeReason = (typeof SHAPE_REASONS)[number];

export type NearestShape = { type: SectionType; flow: ShapeFlow; score: number };

export type ShapeAssessment = {
  shape: LayoutShape;
  fingerprint: string;
  /** Closest existing blocks, best first (at most three). */
  nearest: NearestShape[];
  /** True only when nothing we offer covers the same structural idea. */
  isNew: boolean;
  /** True when the closest block could absorb this with a small change. */
  extendable: boolean;
  reasons: ShapeReason[];
};

/** A layout with almost no structure (a lone heading, a bare image) is never a
 *  new idea - it is a fragment. Below this we never even look. */
function tooThin(shape: LayoutShape): boolean {
  return shape.roles.length + (shape.itemRoles ? 1 : 0) < 3;
}

function reasonsFor(shape: LayoutShape, best: LayoutShape | null): ShapeReason[] {
  if (!best) return ["new-combination"];
  const reasons: ShapeReason[] = [];
  if (shape.itemRoles && !best.itemRoles) reasons.push("new-repeat");
  if (shape.itemRoles && best.itemRoles) {
    const covered = new Set(best.itemRoles);
    if (shape.itemRoles.some((role) => !covered.has(role))) reasons.push("new-item-roles");
  }
  const coveredRoles = new Set(best.roles);
  if (shape.roles.some((role) => !coveredRoles.has(role))) reasons.push("new-combination");
  if (shape.flow !== best.flow) reasons.push("new-flow");
  if (shape.media !== best.media) reasons.push("new-media-weight");
  return reasons.length > 0 ? reasons : ["new-combination"];
}

/**
 * Decide whether an observed layout is something we already offer. Called twice
 * for every idea: once before the owner is ever asked, and again when they say
 * yes - the registry may have grown in between, and a layout we can already
 * build must never become a new one.
 */
export function assessShape(
  observed: LayoutShape,
  catalogue: RegistryShape[] = registryShapes(),
): ShapeAssessment {
  const shape = normalizeShape(observed);
  const fingerprint = shapeFingerprint(shape);
  const ranked = catalogue
    .map((entry) => ({
      type: entry.type,
      flow: entry.shape.flow,
      score: shapeSimilarity(shape, entry.shape),
      raw: entry.shape,
    }))
    .sort((a, b) => b.score - a.score);
  const nearest = ranked.slice(0, 3).map(({ type, flow, score }) => ({
    type,
    flow,
    score: Math.round(score * 100) / 100,
  }));
  const best = ranked[0] ?? null;
  const bestScore = best?.score ?? 0;
  const isNew = !tooThin(shape) && bestScore < COVERED_THRESHOLD;
  return {
    shape,
    fingerprint,
    nearest,
    isNew,
    extendable: isNew && bestScore >= EXTENDABLE_THRESHOLD,
    reasons: isNew ? reasonsFor(shape, best?.raw ?? null) : [],
  };
}
