// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/sections/limits.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

// ---------------------------------------------------------------------------
// Content limits - the single source of truth shared by the editor (soft warning
// + "Shorten" button) and the Convex mutations (hard anti-abuse ceiling). Keeps
// the design balanced by construction: text can't grow long enough to break a
// card, and arrays can't grow long enough to overwhelm a layout.
//
//   soft = recommended length. The editor nudges past this (tooltip + Shorten).
//   hard = ceiling enforced server-side. Legit users never reach it (the soft
//          warning fires far earlier); it only stops direct-API abuse / paste-bombs.
//
// Keyed by the content field's *key* (the last segment of its path, e.g.
// `headline`, or `items.2.title` → `title`), mirroring the LABELS / MULTILINE_KEYS
// pattern in lib/editor/extractFields.ts.
// ---------------------------------------------------------------------------

export type FieldLimit = { soft: number; hard: number };

/** Recommended (soft) character limits per field key. */
const SOFT: Record<string, number> = {
  // hero / headings
  eyebrow: 28,
  headline: 70,
  subheadline: 160,
  // Bottom proof pill in hero.overlay-proof: one scan-friendly fact, not a
  // second paragraph competing with the headline and primary action.
  proofText: 56,
  heading: 64,
  intro: 180,
  subtext: 200,
  // cards / list items
  title: 56,
  description: 180,
  label: 36,
  question: 110,
  answer: 360,
  name: 48,
  role: 56,
  bio: 240,
  // testimonials
  text: 260,
  author: 48,
  // stats / pricing
  value: 14,
  price: 14,
  period: 28,
  currency: 6,
  features: 64,
  bullets: 88,
  // areas
  areas: 48,
  // about / footer / forms
  signatureName: 56,
  businessName: 48,
  tagline: 72,
  submitLabel: 28,
  successMessage: 180,
  note: 180,
  handle: 32,
  placeholder: 48,
  // address
  street: 80,
  postalCode: 16,
  city: 48,
  country: 48,
};

/** Hard ceiling = a generous multiple of the soft limit, with a floor so very
 *  short fields still tolerate the odd long word / pasted token. */
function hardFor(soft: number): number {
  return Math.max(140, soft * 4);
}

/** Resolve the limit for a field key, or null when the key is unconstrained. */
export function fieldLimit(key: string): FieldLimit | null {
  const soft = SOFT[key];
  if (soft === undefined) return null;
  return { soft, hard: hardFor(soft) };
}

/** Last non-index segment of a content path is the field key
 *  ("items.2.title" → "title", "headline" → "headline"). */
export function fieldKeyFromPath(path: string): string {
  const segs = path.split(".");
  for (let i = segs.length - 1; i >= 0; i--) {
    if (!/^\d+$/.test(segs[i])) return segs[i];
  }
  return path;
}

// NOTE: array item caps live in lib/sections/registry.ts (`ARRAY_ITEM_MAX`),
// owned by the section-item add/remove feature. This module intentionally does
// NOT duplicate them - it covers per-field text length + image guards only.

/** Deterministically trim `value` to at most `max` characters, preferring a
 *  word boundary so we never cut mid-word. Used by the editor's "Shorten"
 *  button. Pure + side-effect free so it's trivially testable. */
export function shortenToLimit(value: string, max: number): string {
  if (value.length <= max) return value;
  const slice = value.slice(0, max);
  const lastSpace = slice.lastIndexOf(" ");
  // only break on the space if it isn't unreasonably early (avoids chopping a
  // long single token down to almost nothing)
  const cut = lastSpace > max * 0.6 ? slice.slice(0, lastSpace) : slice;
  // drop a dangling separator / trailing whitespace so it reads cleanly
  return cut.replace(/[\s.,;:!?\-–—]+$/u, "").trim();
}

// ---------------------------------------------------------------------------
// Image guards. A locked aspect-ratio container + object-cover already prevents
// distortion at render time; these stop *degenerate* uploads (a 1×9000 sliver, a
// 30 MB file) from ever entering the system. Enforced client-side (friendly
// inline message, no upload) AND server-side in createAsset (defence in depth).
// ---------------------------------------------------------------------------

export const IMAGE_LIMITS = {
  minDim: 100, // px - anything smaller is unusable as section media
  maxDim: 8000, // px - guards against absurd canvases
  maxBytes: 15 * 1024 * 1024, // 15 MB
  maxAspect: 5, // longest : shortest side
} as const;

export type ImageRejectReason =
  "not_image" | "too_small" | "too_large" | "bad_aspect";

/** Why an image should be rejected, or null when it's acceptable.
 *
 *  `allowVector` (default false): an SVG can carry an inline `<script>`, and blobs
 *  are served inline from Convex storage - so a stored SVG is a latent
 *  stored-content vector (harmless in `<img>`/next-image, but a direct hit on the
 *  storage origin). Photo/media uploads are raster-only and reject it here. The
 *  logo/favicon and owner-restore paths, which legitimately handle vector art,
 *  opt in with `allowVector: true`.
 *
 *  `allowAnyAspect` (default false): the aspect ceiling exists because stored
 *  dims drive *section render layout*. An annotation capture is never rendered
 *  as section media - it is a screenshot of whatever region the user selected,
 *  and a wide, short strip of text is the normal case - so that path opts out.
 *  The minDim floor and the maxDim/maxBytes ceilings still apply, which is what
 *  actually stops a degenerate 1x7000 sliver. */
export function imageRejectReason(p: {
  width: number;
  height: number;
  bytes: number;
  mimeType: string;
  allowVector?: boolean;
  allowAnyAspect?: boolean;
}): ImageRejectReason | null {
  if (!p.mimeType.startsWith("image/")) return "not_image";
  if (!p.allowVector && p.mimeType === "image/svg+xml") return "not_image";
  // maxDim/bytes and aspect are checked BEFORE minDim: an image failing more
  // than one guard at once (e.g. 1x9000 -- under minDim on one axis, over
  // maxDim on the other, and grossly bad-aspect either way) must report the
  // more severe "too_large"/"bad_aspect" reason, not "too_small". Callers
  // that grant a floor-only exemption for brand assets (a real favicon is
  // legitimately tiny) rely on "too_small" meaning ONLY the floor failed --
  // reporting it for a dimension-abuse case would let that exemption dodge
  // the maxDim/aspect ceiling too.
  if (
    p.width > IMAGE_LIMITS.maxDim ||
    p.height > IMAGE_LIMITS.maxDim ||
    p.bytes > IMAGE_LIMITS.maxBytes
  ) {
    return "too_large";
  }
  const aspect = p.width / p.height;
  if (
    !p.allowAnyAspect &&
    (aspect > IMAGE_LIMITS.maxAspect || aspect < 1 / IMAGE_LIMITS.maxAspect)
  ) {
    return "bad_aspect";
  }
  // The floor asks "is this too few pixels to be usable as section media?",
  // which is a question about RASTERS. A vector has no pixels: a 48x48 viewBox
  // partner badge renders as crisply at 400px as at 40. Applying the raster
  // floor to it dropped eight legitimate SVG logos on a real import (backlog
  // 0823), so vectors skip it - and only vectors the caller already opted into
  // (`allowVector`), which the callers decide from the REAL bytes, never from a
  // declared mimeType. Every other guard above still applied.
  const isVector = p.mimeType === "image/svg+xml";
  if (
    !isVector &&
    (p.width < IMAGE_LIMITS.minDim || p.height < IMAGE_LIMITS.minDim)
  ) {
    return "too_small";
  }
  return null;
}

// ---------------------------------------------------------------------------
// SVG screening (brand images only - photo/media uploads reject SVG outright
// via imageRejectReason above). This is fail-closed DETECTION, not sanitization:
// we reject any SVG that carries active content rather than trying to strip it.
// Executed server-side (branding screen action + portability import), where no
// DOM parser exists, so the check runs on entity-decoded text. Assets render
// via <img>/<meta> (scripts inert there); the screened risk is direct
// navigation to the raw blob on the storage origin (security-audit A-7).
// ---------------------------------------------------------------------------

/** Decode numeric character references and the five XML-named entities so an
 *  encoded payload (`jav&#x61;script:`) can't slip past the pattern scan.
 *  Custom named entities can't exist because `<!ENTITY` itself is rejected. */
function decodeXmlEntities(s: string): string {
  return s
    .replace(/&#x([0-9a-f]+);?/gi, (_, hex: string) => codePoint(parseInt(hex, 16)))
    .replace(/&#(\d+);?/g, (_, dec: string) => codePoint(parseInt(dec, 10)))
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&quot;/gi, '"')
    .replace(/&apos;/gi, "'")
    .replace(/&amp;/gi, "&");
}

/** Safe `String.fromCodePoint`: an out-of-range reference (`&#x110000;`) would
 *  otherwise throw RangeError and - since this runs inside the SVG screen -
 *  fail the check open. Drop anything outside the valid Unicode range. */
function codePoint(cp: number): string {
  return Number.isInteger(cp) && cp >= 0 && cp <= 0x10ffff
    ? String.fromCodePoint(cp)
    : "";
}

export type SvgRejectReason = "scripted";

/** Why an SVG should be rejected, or null when it looks like plain vector art.
 *  Rejects script elements, event-handler attributes, javascript:/data-html
 *  URLs, foreignObject (HTML smuggling) and DTD entity declarations.
 *
 *  Deliberately broad: the handler pattern matches ANY `on*=` word (so `only=`
 *  in decorative text content would false-positive), not a curated handler
 *  list. Accepted trade-off - a false positive costs one rejected logo upload
 *  (re-export as PNG); a false negative is the vulnerability. */
export function svgRejectReason(svgText: string): SvgRejectReason | null {
  const decoded = decodeXmlEntities(svgText).toLowerCase();
  // Scheme checks run on a copy with whitespace/control chars removed - URL
  // parsers strip those, so `java\nscript:` still executes.
  const compact = decoded.replace(/[\s\u0000-\u001f]+/g, "");
  if (
    decoded.includes("<script") ||
    decoded.includes("<foreignobject") ||
    decoded.includes("<!entity") ||
    /\son[a-z]+\s*=/.test(decoded) ||
    compact.includes("javascript:") ||
    compact.includes("data:text/html") ||
    smilInjectsDangerousAttribute(compact) ||
    hasExternalUse(compact) ||
    compact.includes("@import")
  ) {
    return "scripted";
  }
  return null;
}

/** SMIL animation can WRITE an attribute at render time, so the payload never
 *  appears in the source as `onload=` and the `\son[a-z]+=` scan above misses
 *  it entirely: `<set attributeName="onload" to="...">` reads as a plain
 *  `attributename="onload"` string, with no whitespace before the `on`.
 *
 *  Scoped to the attributes that actually matter - event handlers and the two
 *  href spellings - so an ordinary animated logo (`attributeName="opacity"`)
 *  still uploads. Runs on the whitespace-stripped copy so
 *  `attributeName = "onload"` cannot dodge it
 *  (backend security audit 2026-07-26, XSS-3). */
function smilInjectsDangerousAttribute(compact: string): boolean {
  if (!/<(set|animate|animatetransform|animatemotion)/.test(compact)) {
    return false;
  }
  return /attributename=["']?(on[a-z]+|href|xlink:href)/.test(compact);
}

/** `<use href="https://.../doc#x">` pulls a fragment from a REMOTE document
 *  into the rendered tree. Internal references (`#id`, the sprite pattern) are
 *  the legitimate use and stay allowed; anything else is not. Same class of
 *  leak as `@import` in an inline `<style>`, rejected above: both turn a
 *  "static image" into an outbound request that discloses the viewer to a
 *  third party, and the fetched document is not screened (XSS-3). */
function hasExternalUse(compact: string): boolean {
  const pattern = /<use[^>]*?(?:xlink:)?href=["']?([^"'>]+)/g;
  for (const match of compact.matchAll(pattern)) {
    if (!match[1].startsWith("#")) return true;
  }
  return false;
}

// ---------------------------------------------------------------------------
// Video upload limits. A small-business site wants a short clip (intro, premises,
// a finished job) - not a film. Caps keep public pages fast and storage sane.
// Enforced client-side (friendly reject before a wasted upload) AND server-side
// in createVideoAsset (anti-abuse). mov is allowed because phones record it.
// ---------------------------------------------------------------------------

/** Absolute fallback caps (the starter tier). Real caps are per-plan
 *  (`PlanLimits.maxVideoMb`/`maxVideoSec`) and passed in by the caller; this is
 *  only used when no plan context is available (e.g. a pure unit check). */
export const VIDEO_LIMITS = {
  maxBytes: 50 * 1024 * 1024, // 50 MB
  maxDurationSec: 120, // 2 min
} as const;

const VIDEO_MIME = /^video\/(mp4|webm|quicktime)$/;

export type VideoRejectReason = "not_video" | "too_large" | "too_long";

/** Why a video should be rejected, or null when it's acceptable. Caps are
 *  injected (per-plan) - defaulting to VIDEO_LIMITS. Duration is optional
 *  (browsers can't always read it); when unknown, only size is gated. */
export function videoRejectReason(
  p: { bytes: number; mimeType: string; durationSec?: number },
  limits: { maxBytes: number; maxDurationSec: number } = VIDEO_LIMITS,
): VideoRejectReason | null {
  if (!p.mimeType.startsWith("video/") || !VIDEO_MIME.test(p.mimeType)) {
    return "not_video";
  }
  if (p.bytes > limits.maxBytes) return "too_large";
  if (p.durationSec != null && p.durationSec > limits.maxDurationSec) {
    return "too_long";
  }
  return null;
}
